apiVersion: v1
kind: Pod
spec:
  containers:
    - name: build
      image: nemerosa/ontrack-build:5.0.1
      command:
        - cat
      tty: true
    - name: postgres
      image: postgres:17
      args: ["-c", "max_connections=300"]
      env:
        - name: POSTGRES_DB
          value: ontrack
        - name: POSTGRES_USER
          value: ontrack
        - name: POSTGRES_PASSWORD
          value: ontrack
      securityContext:
        runAsUser: 999
        runAsGroup: 999
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
      env:
        - name: "discovery.type"
          value: "single-node"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
    - name: rabbitmq
      image: rabbitmq:3.13.7-management
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: ontrack
        - name: RABBITMQ_DEFAULT_PASS
          value: ontrack
    - name: vault
      image: "vault:1.3.2"
      env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "test"
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
  volumes:
    - name: workspace-volume
      emptyDir:
        sizeLimit: 1Gi
