fragment AutoVersioningSourceConfigFragment on AutoVersioningSourceConfig {
    autoApproval
    autoApprovalMode
    postProcessing
    postProcessingConfig
    sourceBranch
    sourceProject
    sourcePromotion
    targetPath
    targetProperty
    targetPropertyRegex
    targetPropertyType
    targetRegex
    upgradeBranchPattern
    validationStamp
    notifications {
        channel
        config
        scope
        notificationTemplate
    }
    prTitleTemplate
    prBodyTemplate
    prBodyTemplateFormat
}