mutation CreateValidationRunById(
    $buildId: Int!,
    $validationStamp: String!,
    $validationRunStatus: String,
    $description: String,
    $dateTime: LocalDateTime,
) {
    createValidationRunById(input: {
        buildId: $buildId,
        validationStamp: $validationStamp,
        validationRunStatus: $validationRunStatus,
        description: $description,
        dateTime: $dateTime,
    }) {
        validationRun {
            ...ValidationRunFragment
        }
        ...PayloadUserErrors
    }
}
