[[appendix-certificates]]
=== Certificates

Some resources (Jenkins servers, ticketing systems, SCM...) will be configured and accessed in Ontrack using the
`https` protocol, possibly with certificates that are not accepted by default.

Ontrack does not offer any mechanism to accept such invalid certificates.

The running JDK has to be configured in order to accept those certificates.

[[appendix-certificates-registration]]
==== Registering a certificate in the JDK

To register the certificate in your JDK:

[source,bash]
----
sudo keytool -importcert \
    -keystore ${JAVA_HOME}/jre/lib/security/cacerts -storepass changeit \
    -alias ${CER_ALIAS} \
    -file ${CER_FILE}
----

To display its content:

[source,bash]
----
sudo keytool -list \
    -keystore ${JAVA_HOME}/jre/lib/security/cacerts \
    -storepass changeit \
    -alias ${CER_ALIAS} \
    -v
----

See the complete documentation at http://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html.

[[appendix-certificates-saving]]
==== Saving the certificate on MacOS

1. Open the Keychain Access utility (Applications -> Utilities)
2. Select your certificate or key from the Certificates or Keys category
3. Choose File -> Export items ...
4. In the Save As field, enter a ".cer" name for the exported item, and click Save.

You will be prompted to enter a new export password for the item.
