[[appendix-deprecations]]
=== Deprecations and migration notes

[[appendix-deprecations-2.35]]
==== Since 2.35

`StructureService` deprecated method:

* The
`getValidationRunsForBuildAndValidationStamp(net.nemerosa.ontrack.model.structure.ID, net.nemerosa.ontrack.model.structure.ID)`
method is deprecated and should be replaced by
`getValidationRunsForBuildAndValidationStamp(net.nemerosa.ontrack.model.structure.ID, net.nemerosa.ontrack.model.structure.ID, int, int)`.

[[appendix-deprecations-2.32]]
==== Since 2.32

Version 2.32 and before do use the H2 database in embedded mode
only. Later versions still support this mode but also support
a <<installation-docker-db-server,server mode>>.

Nothing needs to be done to keep using using the
embedded mode.

To use the new H2 server mode, please refer to the
<<installation>> section.

In <<development,development>> mode, as long as you use the
`dev` profile, nothing will change.

[[appendix-deprecations-2.28]]
==== Since 2.28

BitBucket global configurations are no longer associated with issue services,
only project BitBucket configurations are. This is an alignment with the way
the other SCM connections are working in Ontrack.

Upgrading to 2.28 performs an automated migration of the global configuration
settings to the project ones.

[[appendix-deprecations-2.16]]
==== Since 2.16

WARNING: Support for custom branch and tags patterns in
         <<usage-subversion,Subversion configurations>> has been **removed**.
         Ontrack now supports only standard Subversion structure:
         `project/trunk`, `project/branches` and `project/tags`. This has
         allowed a better flexibility in the association between builds and
         Subversion locations.

Association between builds and Subversion locations is now configured through
a _build revision link_ at branch level. The previous `buildPath` parameter is
converted automatically to the appropriate <<usage-subversion,type of link>>.
