[[migration-postgres]]
=== Migration from H2 to Postgres

Starting from version 3, Ontrack uses Postgres instead of H2 for its back-end.

[[migration-postgres-prerequisites]]
==== Prerequisites

Before you actually start the migration, please make sure you have the following
elements:

* a copy of the H2 database file to migrate (typically a `data.mv.db` file) and
  the associated credentials
* an access to the Postgres database to migrate to and the associated
  credentials
* a copy of the secret files

[TIP]
====
For a <<installation-docker,Docker>> installation, the database is located
at `/var/ontrack/data/database/data.mv.db` and the secret files in
`/var/ontrack/data/files/security/secrets`.
====

[TIP]
====
For a <<installation-rpm,RPM>> or <<installation-debian,Debian>> installation,
the database is located at `/usr/lib/ontrack/database/data.mv.db` and the
secret files in `/usr/lib/ontrack/files/security/secrets`.
====

[[migration-postgres-tool]]
==== Migration tool

The migration tool is part of the Ontrack release and can be downloaded
as `ontrack-postgresql-migration.jar`
in the https://github.com/nemerosa/ontrack/releases[GitHub release page].

[[migration-postgres-run]]
==== Running the migration

Create a directory, called `${MIGRATION}` in the rest of this section, and

* copy the `data.mv.db` database file in this directory
* copy the `ontrack-postgresql-migration.jar` migration tool in this directory

Run the following command:

[source,bash]
----
java -jar ontrack-postgresql-migration.jar
----

By default, the tool will look for the H2 database file in the current
directory, using `ontrack` / `ontrack` as credentials.

By default, the tool will use a Postgres database located at
`jdbc:postgresql://localhost:5432/ontrack`, using `ontrack` / `ontrack` as
credentials.

You can change those default values using the configuration options below.

[[migration-postgres-options]]
==== Migration tool options

Migration options can either be specified on the command line or by
creating a local `application.properties` file.

|===
| Option | Default value | Description

| `ontrack.migration.cleanup`
| `false`
| If set to `true`, all previous tables will be *deleted*. This forces
  a migration from scratch.

| `ontrack.migration.skip-events`
| `false`
| If set to `true`, the events will not be migrated. This can speed up
  the migration but can have side effects since some entities will not
  be associated with their creation event.

| `ontrack.migration.h2.url`
| `jdbc:h2:./data;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DEFRAG_ALWAYS=TRUE`
| JDBC URL to the H2 database

| `ontrack.migration.h2.username`
| `ontrack`
| User used to connect to the H2 database

| `ontrack.migration.h2.password`
| `ontrack`
| Password used to connect to the H2 database

| `ontrack.migration.postgresql.url`
| `jdbc:postgresql://localhost:5432/ontrack`
| JDBC URL to the Postgres database

| `ontrack.migration.postgresql.username`
| `ontrack`
| User used to connect to the Postgres database

| `ontrack.migration.postgresql.password`
| `ontrack`
| Password used to connect to the Postgres database

|===

[[migration-postgres-secrets]]
==== Secret files

The `master.key` and
`net.nemerosa.ontrack.security.EncryptionServiceImpl.encryption` files
must be copied and put in the <<installation,correct place>>.

TIP: For a development environment, put those files in
`work/files/security/secrets`, relatively to the workspace root.
