[[roadmap]]
=== Roadmap

Here are big ideas for the future of Ontrack. No plan yet, just rough ideas
or wish lists.

[[roadmap-jpa]]
==== Use JPA / Hibernate for SQL queries

* caching (no existent today)
* see impact on multi Ontrack cluster

[[roadmap-neo4j]]
==== Using Neo4J as backend

Ontrack basically stores its data as a graph, and Neo4J would be a perfect
match for the storage.

Consider:

* migration
* search engine

[[roadmap-dsl]]
==== Global DSL

The current Ontrack DSL can be used only remotely and cannot be run on the
server.

We could design a DSL which can be run, either:

* remotely - interacting with the HTTP API
* in the server - interacting directly with the services

Additionally, the DSL should be extensible so that extensions can contribute
to it, on the same model than the
https://github.com/jenkinsci/job-dsl-plugin/wiki/Extending-the-DSL[Jenkins Job DSL].

[[roadmap-webhooks]]
==== Web hooks

Have the possibility to register Webhooks in Ontrack in order to notify other
applications about changes and events.
