[[postgres-production-data]]
=== Using production data

Some times, when <<development,developing>> Ontrack or working with
<<extending,extensions>>, it might be useful to copy the production data
locally.

Make sure to have `pg_dump` and `psql` tools available in your working
environment.

NOTE: They are part of the Postgres installation but can be downloaded
individually from the https://www.postgresql.org/download/[download page].

To export the data from the _source_ database in a local `ontrack.sql` file:

[source,bash]
----
pg_dump --dbname ontrack --host <source-host> --port 5432 \
   --username <source-user> > ontrack.sql
----

To import this data into the _target_ database:

[source,bash]
----
psql --dbname ontrack --host <target-host> --port 5432 \
   --username <target-user> < ontrack.sql
----

IMPORTANT: the target database must be _empty_ (no table, no sequences).

When the migration of data is done, do not forget to also copy the secret
files and to put them in the correct location.

[TIP]
====
For a <<installation-docker,Docker>> installation, the secret files are in
`/var/ontrack/data/files/security/secrets`.
====

[TIP]
====
For a <<installation-rpm,RPM>> or <<installation-debian,Debian>> installation,
the secret files are in `/usr/lib/ontrack/files/security/secrets`.
====

[TIP]
====
In the <<development,development environment>>,
the secret files are in
`work/files/security/secrets`, relatively to the workspace root..
====
