[[appendix-deprecations]]
=== Deprecations and migration notes

[[appendix-deprecations-3.38]]
==== Since 3.38

The `PropertyType` interface `getSearchKey` method is now deprecated
and will be removed in a next version. Returning an empty string
or calling the default `super` method is enough.

If the property is searchable, the `getSearchArguments` method
must be implemented instead. See <<extending-properties>> for more
information.

[NOTE]
====
The `searchkey` column in the `properties` database table has been
_deleted_.
====

[[appendix-deprecations-3.35]]
==== Since 3.35

`StructureService` deprecated method:

* The
`getValidationRunsForBuildAndValidationStamp(net.nemerosa.ontrack.model.structure.ID, net.nemerosa.ontrack.model.structure.ID)`
method is deprecated and should be replaced by
`getValidationRunsForBuildAndValidationStamp(net.nemerosa.ontrack.model.structure.ID, net.nemerosa.ontrack.model.structure.ID, int, int)`.

GraphQL schema deprecations:

* `Build.linkedFrom` is now deprecated and must be replaced by either
  `uses` or `usedBy`

[[appendix-deprecations-2.28]]
==== Since 2.28

Bitbucket global configurations are no longer associated with issue services,
only project Bitbucket configurations are. This is an alignment with the way
the other SCM connections are working in Ontrack.

Upgrading to 2.28 performs an automated migration of the global configuration
settings to the project ones.

[[appendix-deprecations-2.16]]
==== Since 2.16

WARNING: Support for custom branch and tags patterns in
         <<usage-subversion,Subversion configurations>> has been **removed**.
         Ontrack now supports only standard Subversion structure:
         `project/trunk`, `project/branches` and `project/tags`. This has
         allowed a better flexibility in the association between builds and
         Subversion locations.

Association between builds and Subversion locations is now configured through
a _build revision link_ at branch level. The previous `buildPath` parameter is
converted automatically to the appropriate <<usage-subversion,type of link>>.
