[[appendix-templating]]
=== Templating engine

The templating engine is used to render some text (plain or in some markup language).

Each template is available to refer to a _context_, typically linked to an event. These context items can be rendered directly, enriched through _source fields_, optional configured, and finally _filtered_ for additional formatting.

The general format of a template is a string which contains expressions like:

[source]
----
${expression}
----

Each expression is either a _function call_ or a _context reference_.

For a function call, the general syntax is:

[source]
----
#.function?name1=value1&name2=value2|filter
----

[NOTE]
====
A function can have any number of named configuration parameters or none at all like below:

[source]
----
#.function
----
====

For a context reference, the general syntax is similar:

[source]
----
ref(.source)?name1=value1&name2=value2|filter
----

The `.source` is optional and allows to refine the context reference.

Examples of valid context references:

[source]
----
project
branch.scmBranch|urlencode
promotionRun.changelog?acrossBranches=false
----

The list of context elements (project, branch, ...) depends on the execution context for the template.

For example, when using <<notifications,notifications>>, it all depends on the _event_ being subscribed to.

To see the list of possible events and their contexts, see <<appendix-events>>.

The next sections list the available sources, functions, contexts and filters.

There are also special objects, known as _templating renderable_, which are specific to some contexts, like <<auto-versioning>> or <<workflows>>.

include::templating/contexts/index.adoc[]

include::templating/sources/index.adoc[]

include::templating/functions/index.adoc[]

include::templating/filters/index.adoc[]

include::templating/renderables/index.adoc[]
