@startuml

class Action<T> {
    id: String
    name: String
    description: String
}

note left of Action
    An ""Action"" contains the information
    about what's possible to do against the
    encapsulating object.

    Examples:

    **Creation of an entity**

    The action is associated with:

    - a link to GET the UI form
    - a mutation to create the entity

    Its type will be ""application/vnd.ontrack.<entity>.create""

    **Updating an entity**

    The action is associated with:

    - a link to GET the UI form
    - a mutation to update the entity

    Its type will be ""application/vnd.ontrack.<entity>.update""

    **Deleting an entity**

    The action is associated with:

    - a mutation to delete the entity

    Its type will be ""application/vnd.ontrack.<entity>.delete""

    **Downloading and uploading an image**

    The action is associated with:

    - a link to GET the image
    - a link to POST the image

    Its type will be ""application/vnd.ontrack.<entity>.image""
end note

Action o--> ActionLink: links "*"

class ActionLink<T> {
    type: String
    method: String
    enabled: (T) -> Boolean
    uri: (T) -> URI?
}

note right of ActionLink
    An ""ActionLink"" refers to a HTTP end point,
    having an ""URI"" and a HTTP ""method"" (like ""PUT""
    or ""POST"") which can be ""enabled"" and has a
    ""type"". The ""type"" identifiers the type of action
    and is structured as a MIME type.
end note

Action o-right-> ActionMutation: mutation "0..1"

class ActionMutation<T> {
    type: String
    mutation: String
    enabled: (T) -> Boolean
}

note right of ActionMutation
    An ""ActionMutation"" refers to a
    GraphQL mutation, which is enabled or
    not according to authorizations or
    state.
end note


interface Actions<T> {
    targetType: KClass<T>
    authorizations: List<Authorization<T>>
}

Actions ..> Action: provides

interface ActionService {
    <T> authorizationsField(type: KClass<T>): GraphQLFieldDefinition?
}

class ActionServiceImpl implements ActionService

ActionServiceImpl o-right-> Actions: actionProviders "*"

@enduml
