[[architecture]]
=== Architecture

[[architecture-modules]]
==== Modules

[plantuml,"modules",png]
----
include::modules.puml[]
----

NOTE: Not all modules nor links are shown here in order to keep some clarity.
The Gradle build files in the source remain the main source of authority.

Modules are used in _ontrack_ for two purposes:

* isolation
* distribution

We distinguish also between:

* core modules
* extension modules

Extension modules rely on the `extension-support` module to be compiled and
tested. The link between the core modules and the extensions is done through
the `extension-api` module, visible by the two worlds.

Modules like `common`, `json`, `tx` or `client` are purely utilitarian
(actually, they could be extracted from `ontrack` itself).

The main core module is the `model` one, which defines both the API of the
Ontrack services and the domain model.

[[architecture-ui]]
==== UI

[[architecture-ui-resources]]
===== Resources

The UI is realized by REST controllers. They manipulate the _model_ and get
access to it through _services_.

In the end, the controllers return _model_ objects that must be decorated by
links in order to achieve Hateoas.

The controllers are not directly responsible for the decoration of the model
objects as _resources_ (model + links). This is instead the responsibility of
the _resource decorators_.

The _model_ objects are not returned as such, often their content needs to be
filtered out. For example, when getting a list of branches for a project, we
do not want each project to bring along its own copy of the project object.
This is achieved using the _model filtering_ technics.

[[architecture-ui-decorators]]
===== Resource decorators

TODO

[[architecture-ui-forms]]
==== Forms

include::architecture-ui-forms.adoc[]

[[architecture-model]]
==== Model

include::concepts.adoc[]

[[architecture-model-filtering]]
==== Model filtering

TODO

include::architecture-jobs.adoc[]

include::architecture-encryption.adoc[]

[[architecture-build-filters]]
==== Build filters

The _build filters_ are responsible for the filtering of _builds_ when listing
them for a _branch_.

[[architecture-build-filters-usage]]
===== Usage

By default, only the last 10 builds are shown for a branch, but a user can
choose to create filters for a branch, and to select them.

The filters he creates are saved for later use:
* locally, in its local browser storage
* remotely, on the server, if he is connected

For a given branch, a filter is identified by a name. The list of available
filters for a branch is composed of those stored locally and of those returned
by the server. The later ones have priority when there is a name conflict.

[[architecture-build-filters-implementation]]
===== Implementation

The `BuildFilter` interface defines how to use a filter. This filter takes as
parameters:

* the current list of filtered builds
* the branch
* the build to filter

It returns two boolean results:

* is the build to be kept in the list?
* do we need to go on with looking for other builds?

The `BuildFilterService` is used to manage the build filters:

* by creating `BuildFilter` instances
* by managing `BuildFilterResource` instances

The service determines the type of `BuildFilter` by using its type, and uses
injected `BuildFilterProvider`s to get an actual instance.

include::reference-services.adoc[]

[[artifacture-technology]]
==== Technology

[[artifacture-technology-client]]
===== Client side

One page only, pure AJAX communication between the client and the server.

* AngularJS
* Angular UI Router
* Angular UI Bootstrap
* Bootstrap
* Less

[[artifacture-technology-server]]
===== Server side

* Spring Boot for the packaging & deployment
* Spring MVC for the REST API
* Spring for the IoC
* Spring Security & AOP for the security layer
* Plain JDBC for the data storage
* H2 in MySQL mode for the database engine

[[artifacture-technology-layers]]
===== Layers

[plantuml,"layers",png]
----
include::architecture-layers.puml[]
----
