@startuml

participant Client
box "Services" #lightblue
    control EncryptionService
    participant CryptoConfidentialKey
    control ConfidentialStore
end box

== Initialisation ==

create ConfidentialStore
-> ConfidentialStore: new

-> EncryptionService: new(ConfidentialStore)
create CryptoConfidentialKey
EncryptionService -> CryptoConfidentialKey: new
CryptoConfidentialKey -> CryptoConfidentialKey
note right
    Key name:
    ""net.nemerosa.ontrack.security.EncryptionServiceImpl.encryption""
end note
CryptoConfidentialKey -> ConfidentialStore: load(key)
ConfidentialStore --> CryptoConfidentialKey: key
alt If key does not exist yet
    CryptoConfidentialKey -> ConfidentialStore: generates random sequence
    ConfidentialStore --> CryptoConfidentialKey: random bytes
    CryptoConfidentialKey -> ConfidentialStore: stores key
end
CryptoConfidentialKey -> CryptoConfidentialKey: stores internal key
CryptoConfidentialKey --> EncryptionService: key

== Encryption ==

Client -> EncryptionService: encrypt(secret)
EncryptionService -> CryptoConfidentialKey: encrypts with internal key
CryptoConfidentialKey --> EncryptionService: encrypted
EncryptionService --> Client: encrypted

== Decription ==

Client -> EncryptionService: decrypt(encrypted)
EncryptionService -> CryptoConfidentialKey: decrypts with internal key
CryptoConfidentialKey --> EncryptionService: decrypted
EncryptionService --> Client: secret

@enduml
