[[architecture-jobs]]
==== Jobs

Ontrack makes a heavy use of _jobs_ in order to schedule regular activities,
like:

* SCM indexation (for SVN for example)
* SCM/build synchronisations
* Branch templating synchronisation
* etc.

Services and extensions are responsible for providing Ontrack with the list of
_jobs_ they want to be executed. They do this by implementing the
`JobProvider` interface that simply returns a collection of `JobRegistration`s
to register at startup.

One component can also register a `JobOrchestratorSupplier`, which provides
also a stream of `JobRegistration`s, but is more dynamic since the list
of jobs to register will be determined regularly.

The _job scheduler_ is in charge to collect all _registered jobs_ and to run
them all.

[[architecture-jobs-overview]]
===== Job architecture overview

This section explains the underlying concepts behind running the jobs in Ontrack.

When a job is registered, it is associated with a schedule. This schedule is dynamic and can be changed
with the time. For example, the indexation of a Git repository for a project is scheduled every 30 minutes,
but then, is changed to 60 minutes. The job registration schedule is then changed to every 60 minutes.

A job provides the following key elements:

* a unique identifier: the _job key_
* a task to run, provided as a `JobRun` interface:

[source,java]
----
@FunctionalInterface
public interface JobRun {
    void run(JobRunListener runListener);
}
----

TIP: The task defined by the job can use the provided `JobRunListener`  to provide feedback on the execution or to
execution messages.

The job task is wrapped into a `Runnable` which is responsible to collect statistics about the job execution, like
number of runs, durations, etc.

In the end, the `JobScheduler` can be associated with a `JobDecorator` to return another `Runnable` layer if needed.

The job scheduler is responsible to orchestrate the jobs. The list of jobs is maintained in memory using an index
associating the job itself, its schedule and its current scheduled task (as a `ScheduledFuture`).

[[architecture-jobs-registration]]
===== Job registration

A `JobRegistration` is the associated of a `Job` and of `Schedule` (run
frequency for the job).

A `Schedule` can be built in several ways:

[source,java]
----
// Registration only, no schedule
Schedule.NONE
// Every 15 minutes, starting now
Schedule.everyMinutes(15)
// Every minute, starting now
Schedule.EVERY_MINUTE
// Every day, starting now
Schedule.EVERY_DAY
// Every 15 minutes, starting after 5 minutes
Schedule.everyMinutes(15).after(5)
----

TIP: see the `Schedule` class for more options.

By enabling the <<configuration-properties,scattering options>>, one can
control the schedule by adding a startup delay at the beginning of the job.

The `Job` interface must define the unique for the job. A key in unique
within a type within a category.

Typically, the category and the type will be fixed (constants) while the
key will depend on the job parameters and context. For example:

[source,java]
----
JobCategory CATEGORY = JobCategory.of("category").withName("My category");
JobType TYPE = CATEGORT.getType("type").withName("My type");
public JobKey getKey() {
   return TYPE.getKey("my-id")
}
----

The `Job` provides also a description, and the desired state of the job:

* disabled or not - might depend on the job parameters and context. For example,
  the job which synchronizes a branch instance with its template will be disable
  if the branch is disabled
* valid or not - when a job becomes invalid, it is not executed, and will be
  unregistered automatically. For example, a Subversion indexation job might
  become invalid if the associated repository configuration has been deleted.

Finally, of course, the job must provide the task to actually execute:

[source,java]
----
public JobRun getTask() {
   return (JobRunListener listener) -> ...
}
----

The task takes as parameter a `JobRunListener`.

IMPORTANT: All job tasks run with _administrator_ privileges. _Job tasks_ can
throw runtime exceptions - they will be caught by the _job scheduler_ and
displayed in the <<admin-console-jobs, administration console>>.
