@startuml
participant Client
participant Server

Client -> Server: GET form
Server -> Server: Creates Form object
Server --> Client: form
Client -> Client: Renders the form
Client -> Server: PUT/POST JSON
@enduml
