@startuml

== Collection of SCM components ==

database SCM

control SCMCatalogCollection

database SCMCatalog

SCMCatalogCollection -> SCM: gets list of repositories
SCMCatalogCollection -> SCMCatalog: registers list of repositories
note right
    Repositories which are no longer
    available are marked
end note

@enduml