[[development]]
=== Development

[[development-setup]]
==== Environment set-up

Following tools must be installed before you can start coding with Ontrack:

* https://www.oracle.com[JDK8u25] or better
* https://www.docker.com/[Docker 1.11] or more recent
* https://docs.docker.com/compose/[Docker Compose 1.6.2] or more recent

[[development-postgres]]
===== Postgres set-up

Starting from release 3, Ontrack uses a Postgresql database for its backend.

By default, the application will try to access it at
`jdbc:postgresql://localhost:5432/ontrack` using `ontrack` / `ontrack` as
credentials.

You can of course set the database yourself, but the best way is to run the
following Gradle command:

[source,bash]
----
./gradlew devInit
----

This will use Docker in order to set up a Postgres database container, exposing
the port `5432` on the host and named `postgresql`.

Following properties are available to personalize this setup:

|===
| Property | Default | Description

| `devPostgresPort` | `5432` | Port the container must expose on the host
| `devPostgresName` | `postgresql` | Name of the container to create

|===

For example, to use the `5555` port:

[source,bash]
----
./gradlew devInit -PdevPostgresPort=5555
----

NOTE: This container is used only for your local development, and is not used
for running the <<testing,integration tests>>, where another container is
automatically created and destroyed.

[[development-build]]
==== Building locally

[source,bash]
----
./gradlew clean build
----

To launch the integration tests or acceptance tests, see <<testing>>.

[[development-launch-gradle]]
==== Launching the application from the command line

Just run:

[source,bash]
----
./gradlew :ontrack-ui:bootRun
----

The application is then available at http://localhost:8080

NOTE: The `dev` profile is activated by default and the working files
and database file will be available under `ontrack-ui/work`.

[[development-launch]]
==== Launching the application in the IDE

Prepare the Web resources by launching:

[source,bash]
----
./gradlew dev
----

In order to launch the application, run the
`net.nemerosa.ontrack.boot.Application` class with
`--spring.profiles.active=dev` as argument.

The application is then available at http://localhost:8080

[[development-web]]
==== Developing for the web

If you develop on the web side, you can enable a
http://livereload.com/[LiveReload] watch on the web resources:

[source,bash]
----
./gradlew watch
----

Upon a change in the web resources, the browser page will be reloaded automatically.

[[development-test]]
==== Running the tests

See <<testing>>.

[[development-ide]]
==== Integration with IDE

[[development-ide-intellij]]
===== With Intellij

* install the Lombok plugin
* in `Build, Execution, Deployment > Compiler > Annotation Processors`, check `Enable annotation processing`

[[delivery]]
==== Delivery

Official releases for Ontrack are available at:

* https://github.com/nemerosa/ontrack/releases[GitHub] for the JAR, RPM
  and Debian packages
* https://registry.hub.docker.com/nemerosa/ontrack[Docker Hub] for the Docker images

See the <<installation>> documentation to know how to install them.

To create a package for delivery, just run:

[source,bash]
----
./gradlew \
   clean \
   test \
   integrationTest \
   dockerLatest \
   build
----

This will create:

* a `ontrack-ui.jar`
* a `nemerosa/ontrack:latest` Docker image in your local registry

TIP: If you're not interested in having a Docker image, just omit the
     `dockerLatest` task.

[[delivery-versioning]]
===== Versioning

The version of the Ontrack project is computed automatically from the current
SCM state, using the
https://github.com/nemerosa/versioning[Gradle Versioning plug-in].

[[delivery-deploying]]
===== Deploying in production

See the <<installation>> documentation.


[[development-glossary]]
==== Glossary

**Form**

Creation or update _links_ can be accessed using the `GET` verb in order to get
a form that allows the client to carry out the creation or update.

Such a form will give information about:

* the fields to be created/updated
* their format
* their validation rules
* their description
* their default or current values
* etc.

The GUI can use those forms in order to automatically (and optionally) display
dialogs to the user. Since the model is responsible for the creation of those
forms, this makes the GUI layer more resilient to the changes.

**Link**

In _resources_, links are attached to _model_ objects, in order to implement a
HATEOAS principle in the application interface.

HATEOAS does not rely exclusively on HTTP verbs since this would not allow a
strong implementation of the actual use cases and possible navigations (which
HATEOAS is all about).

For example, the "Project creation" link on the list of projects is _not_
carried by the sole `POST` verb, but by a `_create` link. This link can be
accessed through verbs:

* `OPTIONS` - list of allowed verbs
* `GET` - access to a form that allows to create the object
* `POST` or `PUT` for an update - actual creation (or update) of the object

**<<model,Model>>**

Representation of a concept in the application. This reflects the _ubiquitous
language_ used throughout the application, and is used in all layers. As POJO
on server side, and JSON objects at client side.

**Repository**

Model objects are persisted, retrieved and deleted through repository objects.
Repositories act as a transparent persistence layer and hides the actual
technology being used.

**Resource**

A resource is a model object decorated with links that allow the client side to
interact with the API following the HATEOAS principle. More than just providing
access to the model structure, those links reflect the actual use cases and the
corresponding navigation. In particular, the links are driven by the
authorizations (a "create" link not being there if the user is not authorized).
See _Link_ for more information.

**Service**

Services are used to provide interactions with the model.
