=== Development

==== Environment set-up

Following tools must be installed before you can start coding with Ontrack:

* https://www.oracle.com[JDK8u25] or better
* https://www.docker.com/[Docker 1.11] or more recent
* https://docs.docker.com/compose/[Docker Compose 1.6.2] or more recent

==== Building locally

[source,bash]
----
./gradlew clean build
----

To launch the integration tests or acceptance tests, see <<testing.adoc>>.

==== Launching the application

Prepare a test environment by running:

[source,bash]
----
./gradlew devInit
----

This will create a Postgresql database running in a Docker container, on port
`5432`.

TIP: To change the port of the Postgresql database container, add
`-PdevPostgresPort=xxx` in all your commands.

NOTE: The Postgresql container run in `restart` mode set to `always` - it will
be restarted when your Docker host boots. It implies that you have to run the
`devInit` task only once.

Prepare the Web resources by launching:

[source,bash]
----
./gradlew dev
----

In order to launch the application, run the
`net.nemerosa.ontrack.boot.Application` class with
`--spring.profiles.active=dev` as argument.

The application is then available at http://localhost:8080

==== Developing for the web

If you develop on the web side, you can enable a
http://livereload.com/[LiveReload] watch on the web resources:

[source,bash]
----
./gradlew watch
----

Upon a change in the web resources, the browser page will be reloaded automatically.

==== Running the tests

See <<testing.adoc>>.

==== Integration with IDE

===== With Intellij

* in `Build, Execution, Deployment > Compiler > Annotation Processors`, check `Enable annotation processing`
* install the Lombok plugin
