[[development]]
=== Development

[[development-setup]]
==== Environment set-up

Following tools must be installed before you can start coding with Ontrack:

* https://www.oracle.com[JDK8u25] or better
* https://www.docker.com/[Docker 1.11] or more recent
* https://docs.docker.com/compose/[Docker Compose 1.6.2] or more recent

[[development-build]]
==== Building locally

[source,bash]
----
./gradlew clean build
----

To launch the integration tests or acceptance tests, see <<testing>>.

[[development-launch]]
==== Launching the application

Prepare the Web resources by launching:

[source,bash]
----
./gradlew dev
----

In order to launch the application, run the
`net.nemerosa.ontrack.boot.Application` class with
`--spring.profiles.active=dev` as argument.

The application is then available at http://localhost:8080

[[development-web]]
==== Developing for the web

If you develop on the web side, you can enable a
http://livereload.com/[LiveReload] watch on the web resources:

[source,bash]
----
./gradlew watch
----

Upon a change in the web resources, the browser page will be reloaded automatically.

[[development-test]]
==== Running the tests

See <<testing>>.

[[development-ide]]
==== Integration with IDE

[[development-ide-intellij]]
===== With Intellij

* install the Lombok plugin
* in `Build, Execution, Deployment > Compiler > Annotation Processors`, check `Enable annotation processing`

[[delivery]]
==== Delivery

Official releases for Ontrack are available at:

* https://github.com/nemerosa/ontrack/releases[GitHub] for the JAR, RPM
  and Debian packages
* https://registry.hub.docker.com/nemerosa/ontrack[Docker Hub] for the Docker images

See the <<installation>> documentation to know how to install them.

To create a package for delivery, just run:

[source,bash]
----
./gradlew \
   clean \
   test \
   integrationTest \
   dockerLatest \
   build
----

This will create:

* a `ontrack-ui.jar`
* a `nemerosa/ontrack:latest` Docker image in your local registry

TIP: If you're not interested in having a Docker image, just omit the
     `dockerLatest` task.

[[delivery-versioning]]
===== Versioning

The version of the Ontrack project is computed automatically from the current
SCM state, using the
https://github.com/nemerosa/versioning[Gradle Versioning plug-in].

[[delivery-deploying]]
===== Deploying in production

See the <<installation>> documentation.
