[[extending-metrics]]
==== Extending metrics

There are several ways to contribute to metrics in Ontrack:

* <<extending-metrics-registry>>
* <<extension-metrics-validation-run-metrics>>
* <<extending-metrics-run-info-listeners>>
* <<extension-metrics-export-service>>

[[extending-metrics-registry]]
===== Meter registry direct usage

[WARNING]
====
Starting from version 2.35/3.35, the metrics framework used by
Ontrack has been migrated to http://micrometer.io/[Micrometer].
This is a breaking change - and the way metrics can be
contributed to by extensions is totally different and
some effort must be done in the migration.
====

In order for extensions to add their own metrics, they can
interact directly with an inject `MeterRegistry` and then
get gauges, timers, counters, etc.

Or they can create some `MeterBinder` beans to register
some gauges at startup time.

Usually, migrating (monotonic) counters and timers will
be straightforward:

[source,kotlin]
----
val meterRegistry: MeterRegistry
meterRegistry.counter("...", tags).increment()
meterRegistry.timer("...", tags).record {
    // Action to time
}
----

For gauge, you have to register them so that they can
be call at any time by the meter registry:

[source,kotlin]
----
val meterRegistry: MeterRegistry
meterRegistry.gauge("...", tags,
    sourceObject,
    { obj -> /* Gets the gauge value from the object */ }
)
----

See the http://micrometer.io/[Micrometer] documentation
for more information on how to register metrics.

[[extension-metrics-validation-run-metrics]]
===== Validation run metrics

Every time a <<validation-runs,validation run>> is created, an event is sent
to all instances of `ValidationRunMetricsExtension`.

You can register an <<extending,extension>> to react to this creation:

[source,kotlin]
----
class InfluxDBValidationRunMetricsExtension(myExtensionFeature: MyExtensionFeature) : AbstractExtension(myExtensionFeature), ValidationRunMetricsExtension {
    override fun onValidationRun(validationRun: ValidationRun) {
        // Does something with the created validation run
    }
}
----

[[extending-metrics-run-info-listeners]]
===== Run info listeners

Builds and validation runs can be associated with some <<builds-run-info,run info>>,
which contain information about the execution time, source and author.

Every time a run info is created, an event is sent to all instances of
`RunInfoListener`.  To react to those run info events, you can also declare
a `@Component` implementing `RunInfoListener`. For example:

[source,kotlin]
----
@Component
class MyRunInfoListener : RunInfoListener {
    override fun onRunInfoCreated(runnableEntity: RunnableEntity, runInfo: RunInfo) {
        // Exports the run info to an external metrics system
    }
}
----

[[extension-metrics-export-service]]
===== Metrics export service

The `MetricsExportService` can be used to export any set of metrics, to any registered
metrics system.

[NOTE]
====
As of now, only <<monitoring-metrics-influxdb,InfluxDB>> is supported.
====

To export a metric, just call the `exportMetrics` method on the service:

[source,kotlin]
----
metricsExportService.exportMetrics(
        "my-metric-name",
        tags = mapOf(
                "tag1" to "name1",
                "tag2" to "name2"
        ),
        fields = mapOf(
                "value1" to value1,
                "value2" to value2
        ),
        timestamp = Time.now()
)
----

[NOTE]
====
Metrics exporters must declared an extension of type `MetricsExportExtension`
in order to be accessible by the `MetricsExportService` service.
====
