[[extending]]
=== Extending Ontrack

Ontrack allows extensions to contribute to the application, and actually, most
of the core features, like <<changelogs, Git change logs>>,
are indeed extensions.

This page explains how to create your own extensions and to deploy them along
Ontrack. The same coding principles apply also for coding core extensions and
to package them in the main application.

WARNING: Having the possibility to have external extensions in Ontrack is very
new and the way to provide them is likely to change (a bit) in the next
versions. In particular, the extension mechanism does not provide classpath
isolation between the "plugins".

[[extending-preparing]]
==== Preparing an extension

In order to create an extension, you have to create a Java project.

TIP: The use of Groovy is also possible.

Note that Ontrack needs at least a JDK8u65 to run.

Your extension needs to a Gradle project and have at least this minimal
`build.gradle` file:

NOTE: Maven might be supported in the future.

      buildscript {
         repositories {
            mavenCentral()
            jcenter()
         }
         dependencies {
            classpath 'net.nemerosa.ontrack:ontrack-extension-plugin:{{ontrack-version}}'
         }
      }
      repositories {
         mavenCentral()
      }
      apply plugin: 'ontrack'

The `buildscript` section declares the version of Ontrack you're building your
extension for. Both the `mavenCentral` and the `jcenter` repositories are needed
to resolve the path for the `ontrack-extension-plugin` since the plugin is
itself published in the Maven Central and some of its dependencies are in
JCenter.

NOTE: The repository declaration might be simplified in later versions.

The plug-in must declare the Maven Central as repository for the dependencies
(Ontrack libraries are published in the Maven Central).

Finally, you can apply the `ontrack` plug-in. This one will:

* apply the `java` plug-in. If you want to use Groovy, you'll have to apply
this plug-in yourself.
* add the `ontrack-extension-support` module to the `compile` configuration
of your extension
* define some tasks used for running, testing and packaging your extension
(see later)

[[extending-id]]
==== Extension ID

Your extension must be associated with an identifier, which will be used
throughout all the extension mechanism of Ontrack.

If the `name` of your extension project looks like `ontrack-extension-<xxx>`,
the `xxx` will be ID of your extension. For example, in the
`settings.gradle` file:

[source,groovy]
----
rootProject.name = 'ontrack-extension-myextension'
----

then `myextension` is your extension ID.

If for any reason, you do not want to use `ontrack-extension-` as a prefix for
your extension name, you must specify it using the `ontrack` Gradle extension
in the `build.gradle` file:

[source,groovy]
----
ontrack {
   id 'myextension'
}
----

[[extending-coding]]
==== Coding an extension

All your code must belong to a package starting with `net.nemerosa.ontrack` in
order to be visible by the Ontrack application.

Typically, this should be like: `net.nemerosa.ontrack.extension.<id>` where
`id` is the ID of your extension.

NOTE: This limitation about the package name is likely to removed in future
versions of Ontrack.

You now must declare your extension to Ontrack by creating an
_extension feature_ class:

[source,java]
----
package net.nemerosa.ontrack.extension.myextension;

import net.nemerosa.ontrack.extension.support.AbstractExtensionFeature;
import net.nemerosa.ontrack.model.extension.ExtensionFeatureOptions;
import org.springframework.stereotype.Component;

@Component
public class MyExtensionFeature extends AbstractExtensionFeature {
    public MyExtensionFeature() {
        super(
            "myextension",
            "My extension",
            "Sample extension for Ontrack",
            ExtensionFeatureOptions.DEFAULT
        );
    }
}
----

The `@Component` annotation makes this extension feature visible by Ontrack.

The arguments for the extension feature constructor are:

* the extension ID
* the display name
* a short description
* the extension options (see below)

[[extending-options]]
==== Extension options

If your extension has some web components (templates, pages, etc.), it must
declare this fact:

[source,java]
----
ExtensionFeatureOptions.DEFAULT.withGui(true)
----

If your extension depends on other extensions, it must declare them. For
example, to depend on GitHub and Subversion extensions, first declare them as
dependencies in the `build.gradle`:

[source,groovy]
----
ontrack {
   uses 'github'
   uses 'svn'
}
----

then, in your code:

[source,java]
----
@Component
public class MyExtensionFeature extends AbstractExtensionFeature {
    @Autowired
    public MyExtensionFeature(
      GitHubExtensionFeature gitHubExtensionFeature,
      SVNExtensionFeature svnExtensionFeature
    ) {
        super(
            "myextension",
            "My extension",
            "Sample extension for Ontrack",
            ExtensionFeatureOptions.DEFAULT
               .withDependency(gitHubExtensionFeature)
               .withDependency(svnExtensionFeature)
        );
    }
}
----

[[extending-testing]]
==== Writing tests for your extension

Additionally to creating unit tests for your extension, you can also write
integration tests, which will run with the Ontrack runtime enabled.

NOTE: This feature is only available starting from version 2.23.1.

When the `ontrack-extension-plugin` is applied to your code, it makes the
`ontrack-it-utils` module available for the compilation of your tests.

In particular, this allows you to create integration tests which inherit from
`AbstractServiceTestSupport`, to inject directly the Ontrack services you need
and to use utility methods to create a test environment.

For example:

[source,java]
----
public MyTest extends AbstractServiceTestSupport {
   @Autowired
   private StructureService structureService
   @Test
   public void sample_test() {
      // Creates a project
      Project p = doCreateProject();
      // Can retrieve it by name...
      asUser().withView(p).execute(() ->
         assertTrue(structureService.findProjectByName(p.getName()).isPresent())
      );
   }
}
----

[[extending-extensions]]
==== List of extension points

Ontrack provides the following extension points:

* <<extending-properties, Properties>> - allows to attach a property to an <<model,entity>>
* <<extending-decorators, Decorators>> - allows to display a decoration for an <<model,entity>>
* <<extending-usermenu, User menu action>> - allows to add an entry in the connected user menu
* <<extending-settings, Settings>> - allows to add an entry in the global settings
* <<extending-metrics, Metrics>> - allows to contribute to the
  <<monitoring,metrics>> exported by Ontrack
* <<extending-event-types, Event types>> - allows to define additional event types.
* <<extending-graphql, GraphQL>> - allows contributions to the <<integration-graphql,GraphQL>> Ontrack schema.
*  **TODO** Entity action - allows to add an action for the page of an entity
*  **TODO** Entity information - allows to add some information into the page of an entity
*  **TODO** Search extension - provides a search end point for global text based searches
*  **TODO** Issue service - provides support for a ticketing system
*  **TODO** SCM service - provides support for a SCM system
*  **TODO** Account management action - allows to add an action into the account management

Other topics:

* <<extending-pages, Creating pages>>
* **TODO** Creating services
* **TODO** Creating jobs

See <<reference-services>> for a list of the core Ontrack services.

[[extending-running]]
==== Running an extension

[[extending-running-gradle]]
===== Using Gradle

To run your extension using Gradle:

[source,bash]
----
./gradlew ontrackRun
----

WARNING: This does not work yet for Ontrack 3.0 (with Postgresql)

This will make the application available at http://localhost:8080

The `ontrackRun` Gradle task can be run directly from Intellij IDEA and if
necessary in debug mode.

TIP: When running with Gradle in your IDE, if you edit some web resources and
want your changes available in the browser, just rebuild your project
(`Ctrl F9` in Intellij) and refresh your browser.

[[extending-running-docker]]
===== Using Docker

In order to deploy your extension in an Ontrack Docker container, start by
building:

[source,bash]
----
./gradlew clean build
----

then run an Ontrack container, configured to fetch its extension directory from
your extension build directory:

      docker run --detach \
         --volume `pwd`/build/libs:/var/ontrack/extensions \
         --publish 8080:8080 \
         nemerosa/ontrack:{{ontrack-version}}

See the <<installation, documentation>> for the Docker options.

[[extending-packaging]]
==== Packaging an extension

Just run:

[source,bash]
----
./gradlew clean build
----

The extension is available as a JAR in `build/libs`.

[[extending-deploying]]
==== Deploying an extension

[[extending-deploying-docker]]
===== Using the Docker image

The <<installation-docker, Ontrack Docker image>> uses the
`/var/ontrack/extensions` volume to load extensions from. Bind this volume to
your host or to a data container to start putting extensions in it.
For example:

[source,bash]
----
docker run --volume /extension/on/host:/var/ontrack/extensions ...
----

You can also create your own image. Create the following `Dockerfile`:

[source]
.Dockerfile
----
# Base Ontrack image
FROM nemerosa/ontrack:<yourversion>
# Overrides the extension directory, as to NOT use a volume
ENV EXTENSIONS_DIR /var/ontrack/your-extension
# Copies the extensions in the target volume
COPY extensions/*.jar /var/ontrack/your-extension/
----

We assume here that your extensions are packaged in an `extensions` folder
at the same level than your `Dockerfile`:

[source]
----
/-- Dockerfile
|-- extensions/
     |-- extension1.jar
     |-- extension2.jar
----

NOTE: When using a _child_ `Dockerfile`, the extension directory has to be
customized because we cannot use the `VOLUME` in this case.

[[extending-deploying-os]]
===== Using the CentOS or Debian/Ubuntu package

The <<installation-rpm, RPM>> and <<installation-debian, Debian>> packages both
use the `/usr/lib/ontrack/extensions` directory for the location of the
extensions JAR files.

You can also create a RPM or Debian package which embeds both Ontrack and your
extensions.

The means to achieve this depend on your build technology but the idea is the
same in all cases:

Your package must:

* put the extension JAR files in `/usr/lib/ontrack/extensions`
* have a dependency on the `ontrack` package

[[extending-deploying-sa]]
===== In standalone mode

When running <<installation-sa, Ontrack directly>>, you have to set the
`loader.path` to a directory containing the extensions JAR files:

[source,bash]
----
java -Dloader.path=/path/to/extensions -jar ... <options>
----

include::extending-properties.adoc[]

include::extending-decorators.adoc[]

include::extending-user-menu.adoc[]

include::extending-pages.adoc[]

include::extending-event-types.adoc[]

include::extending-graphql.adoc[]
