[[extending-pages]]
==== Extending pages

Extensions can also contribute to pages.

[[extending-pages-menus]]
===== Extension menus

Extension pages must be accessible from a location:

* the <<extending-usermenu, global user menu>>
* an <<model,entity>> page

[[extending-pages-menus-global]]
====== From the global user menu

**TODO**

[[extending-pages-menus-entity]]
====== From an entity page

In order for an extension to contribute to the menu of an entity page, you have
to implement the `ProjectEntityActionExtension` interface and extend the
`AbstractExtension`.

[source,java]
----
@Component
public class MyProjectActionExtension extends AbstractExtension implements ProjectEntityActionExtension {
}
----

The `@Component` notation registers the extension in Ontrack.

An action extension, or any <<extending,extension>> is always associated with
an extension feature and this one is typically injected. Other services can be
injected at the same time. For example, our sample extension needs to get a
property on an entity so we inject the `PropertyService`:

[source,java]
----
private final PropertyService propertyService;
@Autowired
public MyProjectActionExtension(MyExtensionFeature extensionFeature, PropertyService propertyService) {
   super(extensionFeature);
   this.propertyService ==== propertyService;
}
----

The `getAction` method returns an optional `Action` for the entity. In our
sample, we want to associate an action with entity if it is a project and if it
has the `MyProperty` property being set:
[source,java]
----
@Override
public Optional<Action> getAction(ProjectEntity entity) {
   if (entity instanceof Project) {
       return propertyService.getProperty(entity, MyPropertyType.class).option()
               .map(p ->
                       Action.of(
                               "my-action",
                               "My action",
                               String.format("my-action/%d", entity.id())
                       )
               );
   } else {
       return Optional.empty();
   }
}
----

The returned `Action` object has the following properties:

* an `id`, uniquely identifying the target page in the extension
* a `name`, which will be used as display name for the menu entry
* a URI fragment, which will be used for getting to the extension end point
(see later). Note that this URI fragment will be prepended by the extension
path. So in our example, the final path for the `SAMPLE` project with id `12`
would be: `extension/myextension/my-action/12`.

[[extending-pages-global]]
===== Extension global settings

**TODO**

[[extending-pages-specific]]
===== Extension page

NOTE: Before an extension can serve some web components, it must be declared as
being GUI related. See the <<extensions, documentation>> to enable this
(`ExtensionFeatureOptions.DEFAULT.withGui(true)`).

The extension must define an AngularJS module file at:

      src/main/resources
        \-- static
           \-- extension
               \-- myextension
                  \-- module.js

The `module.js` file name is fixed and is used by Ontrack to load the web
components of your extension at startup.

This is an AngularJS (1.2.x) module file and can declare its configuration, its
services, its controllers, etc. Ontrack uses
http://angular-ui.github.io/ui-router/site[`UI Router`](), version `0.2.11` for
the routing of the pages, allowing a routing declaration as module level.

For our example, we want to declare a page for displaying information for
`extension/myextension/my-action/{project}` where `{project}` is the ID of
one project:

[source,javascript]
----
angular.module('ontrack.extension.myextension', [
        'ot.service.core',
        'ot.service.structure'
    ])
    // Routing
    .config(function ($stateProvider) {
        $stateProvider.state('my-action', {
            url: '/extension/myextension/my-action/{project}',
            templateUrl: 'extension/myextension/my-action.tpl.html',
            controller: 'MyExtensionMyActionCtrl'
        });
    })
    // Controller
    .controller('MyExtensionMyActionCtrl', function ($scope, $stateParams, ot, otStructureService) {
        var projectId ==== $stateParams.project;

        // View definition
        var view ==== ot.view();
        view.commands ==== [
            // Closing to the project
            ot.viewCloseCommand('/project/' + projectId)
        ];

        // Loads the project
        otStructureService.getProject(projectId).then(function (project) {
            // Breadcrumbs
            view.breadcrumbs ==== ot.projectBreadcrumbs(project);
            // Title
            view.title ==== "Project action for " + project.name;
            // Scope
            $scope.project ==== project;
        });
    })
;
----

The routing configuration declares that the end point at
`/extension/myextension/my-action/{project}` will use the
`extension/myextension/my-action.tpl.html` view and the
`MyExtensionMyActionCtrl` controller defined below.

The `ot` and `otStructureService` are Ontrack Angular services, defined
respectively by the `ot.service.core` and `ot.service.structure` modules.

The `MyExtensionMyActionCtrl` controller:

* gets the project ID from the state (URI) definition
* it defines an Ontrack view, and defines a close command to go back to the
  project page
* it then loads the project using the `otStructureService` service  and upon
  loading completes some information into the view

Finally, we define a template at:

      src/main/resources
        \-- static
           \-- extension
               \-- myextension
                  \-- extension/myextension/my-action.tpl.html

which contains:

[source,html]
----
<ot-view>
    Action page for {{project.name}}.
</ot-view>
----

The `ot-view` is an Ontrack directive which does all the layout magic for you.
You just have to provide the content.

Ontrack is using http://getbootstrap.com/[Bootstrap 3.x] for the layout and
basic styling, so you can start structuring your HTML with columns, rows,
tables, etc. For example:

[source,html]
----
<ot-view>
   <div class="row">
      <div class="col-md-12">
         Action page for {{project.name}}.
      </div>
   </div>
</ot-view>
----

[[extending-pages-api]]
===== Extension API

**TODO**

[[extending-pages-resources]]
===== Extension API resource decorators

**TODO**
