[[extension-label-provider]]
==== Label providers

<<projects-labels,Labels>> can be created and associated
manually with projects.

Ontrack allows also some automation of this process
using the concept of a _label provider_.

[NOTE]
====
Labels created and associated to projects by
_label providers_ cannot be managed manually:
they cannot be edited, deleted or unselected.
====

===== Implementation

A _label provider_ is a `Service` which extends
the `LabelProvider` class and returns a list of
labels for a project.

For example, we could have a _label provider_ which
associates a "quality" label according to the "health"
of the validation stamps in all "main" branches
of the project. The label category would be "quality"
and different names could be "high", "medium" and "low".

The code would look like:

[source,kotlin]
----
@Service
class QualityLabelProvider : LabelProvider {

    override val name: String = "Quality"

    override val isEnabled: Boolean = true

    override fun getLabelsForProject(project: Project): List<LabelForm> {
      // Computes quality of the project
      val quality: String = ...
      // Returns a label
      return listOf(
         LabelForm(
            category = "quality",
            name = quality,
            description = "",
            color = ... // Computes color according to quality
         )
      )
   }
}
----

===== Activation

Even if you code such a _label provider_, nothing will happen
until you activate the collection of labels.

Ontrack disables this collection by default, because there is no
default label provider and that would be a useless job.

To activate the label collection job, just set the
`ontrack.config.job-label-provider-enabled`
<<configuration-properties,configuration property>>
to `true`.
