[[extending-graphql]]
==== Extending GraphQL

Extensions can contribute to the Ontrack <<integration-graphql,GraphQL>> core
schema:

* custom types
* root queries
* additional fields in <<model,project entities>>

[[extending-graphql-module]]
===== Preparing the extension

In your extension module, import the `ontrack-ui-graphql` module:

[source,groovy]
----
dependencies {
   compile "net.nemerosa.ontrack:ontrack-ui-graphql:${ontrackVersion}"
}
----

If you want to write <<extending-graphql-testing,integration tests>> for your
GraphQL extension, you have to include the GraphQL testing utilities:

[source,groovy]
----
dependencies {
   compile "net.nemerosa.ontrack:ontrack-ui-graphql:${ontrackVersion}:tests"
}
----

[[extending-graphql-types]]
===== Custom types

To define an extra type, you create a component which implements the
`GQLType` interface:

[source,java]
----
@Component
public class PersonType implements GQLType {
    @Override
    public GraphQLObjectType getType() {
        return GraphQLObjectType.newObject()
                .name("Person")
                .field(f -> f.name("name")
                        .description("Name of the person")
                        .type(GraphQLString)
                )
                .build();
    }
}
----

TIP: See the https://github.com/graphql-java/graphql-java[graphql-java]
documentation for the description of the type construction.

You can use this component in other ones, like in queries, field definitions
or other types, like shown below:

[source,java]
----
@Component
public class AccountType implements GQLType {

    private final PersonType personType;

    @Autowired
    public AccountType (PersonType personType) {
        this.personType = personType;
    }

    @Override
    public GraphQLObjectType getType() {
        return GraphQLObjectType.newObject()
                .name("Account")
                .field(f -> f.name("username")
                        .description("Account name")
                        .type(GraphQLString)
                )
                .field(f -> f.name("identity")
                        .description("Identity")
                        .type(personType.getType())
                )
                .build();
    }
}
----

You can also create GraphQL types dynamically by using introspection of your
model classes.

Given the following model:

[source,java]
----
@Data
public class Person {
   private final String name;
}
@Data
public class Account {
   private final String username;
   private final Person identity;
}
----

You can generate the `Account` type by using:

[source,java]
----
@Override
public GraphQLObjectType getType() {
   return GraphQLBeanConverter.asObjectType(Account.class);
}
----

CAUTION: The `GraphQLBeanConverter.asObjectType` is still very
*experimental* and its implementation is likely to change in the next versions
of Ontrack.

[[extending-graphql-queries]]
===== Root queries

Your extension can contribute to the root query by creating a component
implementing the `GQLRootQuery` interface:

[source,java]
----
@Component
public class AccountGraphQLRootQuery implements GQLRootQuery {

    private final AccountType accountType;

    @Autowired
    public AccountGraphQLRootQuery(AccountType accountType) {
        this.accountType = accountType;
    }

    @Override
    public GraphQLFieldDefinition getFieldDefinition() {
        return GraphQLFieldDefinition.newFieldDefinition()
                .name("accounts")
                .argument(a -> a.name("username")
                        .description("User name pattern")
                        .type(GraphQLString)
                )
                .type(accountType.getType())
                .dataFetcher(...)
                .build();
    }
}
----

This root query can then be used into your GraphQL queries:

[source]
----
{
   accounts(username: "admin*") {
      username
      identity {
         name
      }
   }
}
----

[[extending-graphql-fields]]
===== Extra fields

The Ontrack GraphQL extension mechanism allows contributions to the
<<model,project entities>> like the projects, builds, etc.

For example, to contribute a `owner` field of type `Account` on the `Branch`
project entity:

[source,java]
----
@Component
public class BranchOwnerGraphQLFieldContributor
   implements GQLProjectEntityFieldContributor {

   private final AccountType accountType;

   @Autowired
   public BranchOwnerGraphQLFieldContributor(AccountType accountType) {
      this.accountType = accountType;
   }

   @Override
   public List<GraphQLFieldDefinition> getFields(
         Class<? extends ProjectEntity> projectEntityClass,
         ProjectEntityType projectEntityType) {
     return Collections.singletonList(
             GraphQLFieldDefinition.newFieldDefinition()
                     .name("owner")
                     .type(accountType.getType())
                     .dataFetcher(GraphqlUtils.fetcher(
                        Branch.class,
                        (environment, branch) -> return ...
                     ))
                     .build()
     );
}
----

You can now use the `owner` field in your queries:

[source]
----
{
   branches(id: 1) {
      name
      project {
         name
      }
      owner {
         username
         identity {
            name
         }
      }
   }
}
----

[[extending-graphql-scalars]]
===== Built-in scalar fields

The Ontrack GraphQL module adds the following scalar types, which you can
use in your field or type definitions:

* `GQLScalarJSON.INSTANCE` - maps to a `JsonNode`
* `GQLScalarLocalDateTime.INSTANCE` - maps to a `LocalDateTime`

You can use them directly in your definitions:

[source,java]
----
...
.field(f -> f.name("content").type(GQLScalarJSON.INSTANCE))
.field(f -> f.name("timestamp").type(GQLScalarLocalDateTime.INSTANCE))
...
----

[[extending-graphql-testing]]
===== Testing GraphQL

In your tests, create a test class which extends `AbstractQLITSupport` and
use the `run` method to execute a GraphQL query:

[source,groovy]
----
MyTestIT extends AbstractQLITSupport {
   @Test
   void my_test() {
     def p = doCreateProject()
     def data = run("""{
      projects(id: ${p.id}) {
         name
      }
     }""")
     assert data.projects.first().name == p.name
   }
}
----

TIP: While it is possible to run GraphQL tests in Java, it's easier to do
using Groovy.
