[[extension-free-text-annotations]]
==== Free text annotations

Some free text can be entered as description for some
elements of the <<model,model>> and can be automatically extended
with hyperlinks.

See <<validation-run-status-hyperlink>> for this
feature in the validation run statuses.

Using <<extending,extensions>>, it is possible to extend
this hyperlinked to other elements.

For example, let's imagine that we have a system
where all references like `[1234]` can be replaced
to a link to `http://reference/1234` with `1234`
as a text.

For this, you have to create a `@Component` bean which
implements the `FreeTextAnnotatorContributor` interface.

The `getMessageAnnotators` returns a list
of `MessageAnnotator`s used to transform the text
into a tree of nodes (typically some HTML).

In our example, this can give something like:

[source,kotlin]
----
@Component
class RefFreeTextAnnotatorContributor : FreeTextAnnotatorContributor {
    override fun getMessageAnnotators(entity: ProjectEntity): List<MessageAnnotator> {
        val regex = "\\[(d+)\\]".toRegex()
        return listOf(
                RegexMessageAnnotator(
                        "\\[d+]\\"
                ) { match ->
                    val result = regex.matchEntire(match)
                    result
                            ?.let {
                                val id = it.groups[1].value.toInt(10)
                                MessageAnnotation.of("a")
                                        .attr("href", "http://reference/$id")
                                        .text(id.toString())
                            }
                            ?: match
                }
        )
    }
}
----

This component returns a single `RegexMessageAnnotator` (other implementations are of course possible,
but this one is very convenient) which, given a regular expression, uses any match to transform
into something else.

In our example, we extract the ID from the expression and return a link.
