[[extending]]
== Extending Ontrack

Ontrack is built around a core code and a list of extensions. This simplifies the maintenance of the application as a whole.

[NOTE]
====
Since version 5, Ontrack does not support any longer external extensions.
====

The rest of this chapter documents _internal_ extension modules.

[[extending-id]]
=== Extension ID

Your extension must be associated with an identifier, which will be used
throughout all the extension mechanism of Ontrack.

If the `name` of your extension module looks like `ontrack-extension-<xxx>`,
the `xxx` will be ID of your extension.

The extension module must be a folder at the root of the `ontrack` repository. The module must be declared:

* in `settings.gradle.kts`:

[source,kotlin]
----
include(":ontrack-extension-xxx")
----

* `ontrack-ui/build.gradle.kts`:

[source,kotlin]
----
runtimeOnly(project(":ontrack-extension-xxx"))
----

[[extending-coding]]
=== Coding an extension

All your code must belong to a package starting with `net.nemerosa.ontrack` in
order to be visible by the Ontrack application.

Typically, this should be like: `net.nemerosa.ontrack.extension.<id>` where
`id` is the ID of your extension.

You now must declare your extension to Ontrack by creating an
_extension feature_ class:

[source,kotlin]
----
package net.nemerosa.ontrack.extension.myextension

import net.nemerosa.ontrack.extension.support.AbstractExtensionFeature
import net.nemerosa.ontrack.model.extension.ExtensionFeatureOptions
import org.springframework.stereotype.Component

@Component
class MyExtensionFeature : AbstractExtensionFeature(
    "myextension",
    "My extension",
    "Sample extension for Ontrack",
    ExtensionFeatureOptions.DEFAULT
)
----

The `@Component` annotation makes this extension feature visible by Ontrack.

The arguments for the extension feature constructor are:

* the extension ID
* the display name
* a short description
* the extension options (see below)

[[extending-options]]
=== Extension options

If your extension has some web components (templates, pages, etc.), it must
declare this fact:

[source,kotlin]
----
ExtensionFeatureOptions.DEFAULT.withGui(true)
----

If your extension depends on other extensions, it must declare them. For
example, to depend on GitHub and SCM extensions, first declare them as
dependencies in the `build.gradle`:

[source,groovy]
----
ontrack {
   uses 'github'
   uses 'scm'
}
----

then, in your code:

[source,java]
----
@Component
public class MyExtensionFeature extends AbstractExtensionFeature {
    @Autowired
    public MyExtensionFeature(
      GitHubExtensionFeature gitHubExtensionFeature,
      SCMExtensionFeature scmExtensionFeature
    ) {
        super(
            "myextension",
            "My extension",
            "Sample extension for Ontrack",
            ExtensionFeatureOptions.DEFAULT
               .withDependency(gitHubExtensionFeature)
               .withDependency(scmExtensionFeature)
        );
    }
}
----

[[extending-testing]]
=== Writing tests for your extension

Additionally to creating unit tests for your extension, you can also write
integration tests, which will run with the Ontrack runtime enabled.

NOTE: This feature is only available starting from version 2.23.1.

When the `ontrack-extension-plugin` is applied to your code, it makes the
`ontrack-it-utils` module available for the compilation of your tests.

In particular, this allows you to create integration tests which inherit from
`AbstractServiceTestJUnit4Support`, to inject directly the Ontrack services you need
and to use utility methods to create a test environment.

For example:

[source,kotlin]
----
class MyTest: AbstractServiceTestSupport() {
   @Autowired
   private lateinit var structureService: StructureService
   @Test
   fun sample_test() {
      // Creates a project
      val p = doCreateProject()
      // Can retrieve it by name...
      asUser().withView(p).execute {
         assertTrue(structureService.findProjectByName(p.getName()).isPresent())
      }
   }
}
----

[[extending-extensions]]
=== List of extension points

Ontrack provides the following extension points:

* <<extending-properties, Properties>> - allows to attach a property to an <<model,entity>>
* <<extending-decorators, Decorators>> - allows to display a decoration for an <<model,entity>>
* <<extending-usermenu, User menu action>> - allows to add an entry in the connected user menu
* <<extending-settings, Settings>> - allows to add an entry in the global settings
* <<extending-metrics, Metrics>> - allows to contribute to the
  <<monitoring,metrics>> exported by Ontrack
* <<extending-event-types, Event types>> - allows to define additional event types.
* <<extending-graphql, GraphQL>> - allows contributions to the <<integration-graphql,GraphQL>> Ontrack schema.
* <<extending-encryption, Encryption key store>> - allows to define a custom store for the <<integration-encryption,encryption keys>>.
*  **TODO** Entity action - allows to add an action for the page of an entity
*  **TODO** Entity information - allows to add some information into the page of an entity
*  **TODO** Search extension - provides a search end point for global text based searches
*  **TODO** Issue service - provides support for a ticketing system
*  **TODO** SCM service - provides support for a SCM system
*  **TODO** Account management action - allows to add an action into the account management

Other topics:

* <<extending-pages, Creating pages>>
* **TODO** Creating services
* **TODO** Creating jobs

See <<reference-services>> for a list of the core Ontrack services.

include::extending-properties.adoc[]

include::extending-decorators.adoc[]

include::extending-user-menu.adoc[]

include::extending-pages.adoc[]

include::extending-event-types.adoc[]

include::extending-validation-data.adoc[]

include::extending-graphql.adoc[]

include::extending-cache.adoc[]

include::extending-metrics.adoc[]

include::extending-kotlin.adoc[]

include::extending-settings.adoc[]

include::extending-security.adoc[]

include::extending-encryption.adoc[]

include::extension-free-text-annotations.adoc[]

include::extension-label-provider.adoc[]

include::extending-promotion-checks.adoc[]

include::extending-search.adoc[]
