[[extending-search]]
==== Extending the search

The Search capabilities of Ontrack can be extended through extensions
and the core capabilities are also coded through extensions.

A Search extension is a component which implements the `SearchIndexer` interface.

[NOTE]
====
In versions 3.40 and before, search extensions were done using `SearchProvider`
implementations. Search was always done dynamically, without going through
an index, making it particularly slow on big volumes or when scanning
external systems.

The `SearchProvider` is now deprecated and will be removed in version 4 of
Ontrack, to be replaced exclusively by ElasticSearch.
====

[[extending-search-overview]]
===== Search indexer overview

A `SearchIndexer` is responsible for two things:

* feeding a search index
* transforming found index entries into displayable search results

The `SearchIndexer` must be parameterized by a `SearchItem` class -
see

The `indexerName` is the display name for the indexer, used to log
information or to name the <<extending-search-indexation-jobs,indexation jobs>>.

Indexation jobs can be totally disabled by setting `true` as
the `isIndexationDisabled` property. They cannot even be triggered
manually - set `isIndexationDisabled` to `true` when search indexes
are not applicable. For example, some `SearchIndexer` instances
might be fed by other indexers.

The `indexerSchedule` is used to set a schedule to the
<<architecture-jobs,indexation job>>. It defaults to `Schedule.NONE`
meaning that the job can be run only manually. Set another
schedule for an automated job.

The `indexName` defines the name of the technical index used
by this `SearchIndexer` - when using ElasticSearch, it corresponds
to the name of ElasticSearch index to use. The index can be configured
by setting the `indexMapping` property - see <<extending-search-indexation-mapping>>
for more information on this subject.

[NOTE]
====
At Ontrack startup time, all indexes are created (in ElasticSearch)
and their mapping updated.
====

The `searchResultType` defines the type of result returned by an index
search capability. It's used:

1. to provide a user a way to filter on the types of results
2. a way for the front-end to associate an <<extending-search-result-icon,icon>>
   to the type of result

For example:

[source,kotlin]
----
@Component
class MySearchIndexer: SearchIndexer<MySearchItem> {
    override val searchResultType = SearchResultType(
            feature = feature.featureDescription,
            id = "my-result",
            name = "My result",
            description = "Use a comma-separated list of tokens"
    )
}
----

The `feature` is the `ExtensionFeature` associated with this
`SearchIndexer` (see <<extending-coding>>).

The `description` property is used to describe the type of search
token one should use to find this type of result (when
applicable).

[[extending-search-indexation-process]]
===== Search indexation

The `indexAll` method is called by the system when indexation
job for this indexer is enabled (it is by default, unless
`isIndexationDisabled` returns `true`).

It must:

* loop over all items to be indexed for a search (for example: all projects for the project indexer)
* transform all those items into instances of the `SearchItem` class associaed
  with this indexer (for example: keeping only the project ID, its name and description)
* call the the provided `processor` function

[TIP]
====
The `indexAll` method is called by the system user.
====

For example:

[source,kotlin]
----
override fun indexAll(processor: (ProjectSearchItem) -> Unit) {
    structureService.projectList.forEach { project ->
        processor(ProjectSearchItem(project))
    }
}
----

Behind the scene, the indexation job will send the items to index
to an index service in batches (which makes the indexation quite
performant).

The batch size is set by default to `1000` but can be:

1. configured using the `ontrack.config.search.index.batch` <<configuration-properties,property>>
2. set explicitly using the `indexBatch` property of the `SearchIndexer` (this takes
   precedence)

[[extending-search-indexation-result]]
===== Search results

When a search is performed, the `SearchService` will call
the `toSearchResult` method of the `SearchIndexer` in order
to transform an indexed item into a result which can be displayed
to the user.

[TIP]
====
See the documentation of the `SearchIndexer.toSearchResult`
and of `SearchResult` for a complete information.
====

Usually, the indexer will:

* load the actual Ontrack object or extract information from the indexed item
  (this latter method is preferred for performance reasons)
* in particular, it'll check if the target object makes sense: does
  it still exist? Is it authorized to the current user?
* setup a `SearchResult` instance to describe the result

For example, for the build indexer:

[source,kotlin]
----
override fun toSearchResult(id: String, score: Double, source: JsonNode): SearchRe
        structureService.findBuildByID(ID.of(id.toInt()))?.run {
            SearchResult(
                    title = entityDisplayName,
                    description = description ?: "",
                    uri = uriBuilder.getEntityURI(this),
                    page = uriBuilder.getEntityPage(this),
                    accuracy = score,
                    type = searchResultType
            )
        }
----

In this example:

* `findBuildByID` checks both the existence of the build
  and if it is accessible by the current user, returning `null`
  when not available
* the `title` of the result is set of the complete build name (including project and branch name)
* the `uri` and `page` can be computed using an injected `URIBuilder`
* the `accuracy` is the score returned by ElasticSearch
* for the `type` just use the `searchResultType` of the indexer

NOTE: As of now, the `accuracy` is used for sorting results, but is not displayed

[CAUTION]
====
The `toSearchResult` runs with the authorizations of the
user who is performing the search. Results should be filtered
accordingly using an injected `SecurityService`. If not, either
the search will fail because of forbidden accesses or the final
access will be rejected.
====

[[extending-search-item]]
===== Search index items

The `SearchItem` class used to parameterize the `SearchIndexer`
must return two values:

* `id` - the unique ID of this item in the index
* `fields` - a map of values to store together with the index

Most of the times, you can define:

* a primary constructor listing the properties who want to store
* a secondary constructor using the domain model of Ontrack

Example for the Git commit indexer:

[source,kotlin]
----
class GitCommitSearchItem(
        val projectId: Int,
        val gitType: String,
        val gitName: String,
        val commit: String,
        val commitShort: String,
        val commitAuthor: String,
        val commitMessage: String
) : SearchItem {

    constructor(project: Project, gitConfiguration: GitConfiguration, commit: GitCommit) : this(
            projectId = project.id(),
            gitType = gitConfiguration.type,
            gitName = gitConfiguration.name,
            commit = commit.id,
            commitShort = commit.shortId,
            commitAuthor = commit.author.name,
            commitMessage = commit.shortMessage
    )

    override val id: String = "$gitName::$commit"

    override val fields: Map<String, Any?> = asMap(
            this::projectId,
            this::gitType,
            this::gitName,
            this::commit,
            this::commitAuthor,
            this::commitShort,
            this::commitMessage
    )
}
----

For the `fields` of the item, try to get only simple types
or list of simple types.

The `asMap` utility method is optional and can be replaced by
a direct map construction. However, it avoids to hard-code
the field names and uses the property references instead.

[[extending-search-indexation-mapping]]
===== Search indexation mapping

By default, indexes are mapped automatically to the provided fields
(like in ElasticSearch) but explicit mappings can be provided to:

* disable the indexation of some fields (like the `projectId` in the
  example above - while this field is needed for creating a search
  result, it should not be used for searches)
* set a type, like keyword or text (the search won't work the
  same way)
* boosting the search result score on some fields (a match on
  a key might be better than a match on a free description text)

[NOTE]
====
While the `SearchIndexer` mechanism has been made independent on
ElasticSearch, the concept of mapping is very close to this
application, in particular the mapping types (see below).
====

In order to specify a mapping, the `indexMapping` of the `SearchIndexer`
must return an instance of `SearchIndexMapping`.

While it's possible to build such an instance manually, it's more
convenient to use the provided DSL. For example, for the Git commit
indexer mentioned above:

[source,kotlin]
----
override val indexMapping: SearchIndexMapping? = indexMappings<GitCommitSearchItem> {
    +GitCommitSearchItem::projectId to id { index = false }
    +GitCommitSearchItem::gitType to keyword { index = false }
    +GitCommitSearchItem::gitName to keyword { index = false }
    +GitCommitSearchItem::commit to keyword { scoreBoost = 3.0 }
    +GitCommitSearchItem::commitShort to keyword { scoreBoost = 2.0 }
    +GitCommitSearchItem::commitAuthor to keyword()
    +GitCommitSearchItem::commitMessage to text()
}
----

The syntax is:

[source]
----
+<SearchItem::property>> [to <type>[ { <configuration> }]]*
----

The type for the property can be set using:

* `id` for a `long`
* `keyword`
* `text`
* any other type supported by ElasticSearch using `type("typeName")

The configuration is optional but accepts the following properties:

* `index: Boolean` - unset by default - to specify if this property must be indexed or not
* `scoreBoost: Double` - multiplicator for the significance of a match on this field
  (similar to the boost indicator in ElasticSearch)

A property can be associated with two types, for example when a field
can be both considered as a keyword or as plain text.

[source,kotlin]
----
+SearchItem::myProperty to keyword { scoreBoost = 2.0 } to text()
----

[[extending-search-indexation-jobs]]
===== Search indexation jobs

Unless its `isIndexationDisabled` property returns `true`, every
`SearchIndexer` is associated with a <<architecture-jobs,job>> which
runs the <<extending-search-indexation-process,indexation>> of all
items.

By default, those jobs must be launched manually but the `indexSchedule`
can be used to define a run schedule.

Additionally, there is "All re-indexations" job which launches
all re-indexations ; this is useful when migrating Ontrack
to a deployment using ElasticSearch or to reset all indexes.

[[extending-search-result-icon]]
===== Search result icon


