[[extending-decorators]]
==== Extending decorators

A decorator is responsible to display a decoration (icon, text, label, etc.)
close to an <<model, entity>> name, in the entity page itself or in a list
of those entities. Extensions can contribute to create new ones.

A _decorator_ is the association some Java components and a HTML template to
render it on the screen.

[[extending-decorators-java]]
===== Java components

First, a decorator must be associated with some data. You can use any type,
like a `String`, an `enum` or any other  invariant POJO. In our sample,
 we'll take a `String`, which is the value of the `MyProperty` property
 described as example in <<extending-properties>>.

Then, you create the _decorator_ itself, by implementing the
`DecorationExtension` interface and extending the `AbstractExtension`. The
parameter type is the decorator data defined above.

[source,java]
----
@Component
public class MyDecorator extends AbstractExtension implements DecorationExtension<String> {
}
----

The `@Component` notation registers the decorator in Ontrack.

A decorator, or any <<extending, extension>> is always associated with an
extension feature and this one is typically injected. Other services can be
injected at the same time. For example, our sample decorator needs to get a
property on an entity so we inject the `PropertyService`:

[source,java]
----
private final PropertyService propertyService;
@Autowired
public MyDecorator(MyExtensionFeature extensionFeature, PropertyService propertyService) {
   super(extensionFeature);
   this.propertyService ==== propertyService;
}
----

Now, several methods need to be implemented:

* `getScope` returns the set of <<model, entities>> the decorator can be
applied to. For example, if your property can be applied only on projects, you
can return:

[source,java]
----
@Override
public EnumSet<ProjectEntityType> getScope() {
   return EnumSet.of(ProjectEntityType.PROJECT);
}
----

* `getDecorations` returns the list of decorations for an entity. In our case,
we want to return a decoration only if the project is associated with the
`MyProperty` property and return its value as decoration data.

[source,java]
----
@Override
public List<Decoration<String>> getDecorations(ProjectEntity entity) {
  return propertyService.getProperty(entity, MyPropertyType.class).option()
          .map(p -> Collections.singletonList(
                  Decoration.of(
                          MyDecorator.this,
                          p.getValue()
                  )
          ))
          .orElse(Collections.emptyList());
}
----

[[extending-decorators-web]]
===== Web components

A HTML fragment (or template) must be created at:

      src/main/resources
        \-- static
           \-- extension
               \-- myextension
                  \-- decoration
                     \-- net.nemerosa.ontrack.extension.myextension.MyDecorator.tpl.html

NOTE: Replace `myextension`, the package name and the decorator type
accordingly of course.

The `tpl.html` will be used as a template on the client side and will have
access to the `Decoration` object. Typically, only its `data` field, of the
decoration data type, will be used.

The template is used the
https://docs.angularjs.org/guide/templates[AngularJS template] mechanism.

For example, to display the decoration data as bold text in our sample:

[source,html]
----
<!-- In this sample, `data` is a string -->
<b>{{decoration.data}}</b>
----
