[[extending-validation-data]]
==== Extending validation data

If built-in <<validation-stamps-data,validation data types>> are not enough,
additional ones can be created using the extension mechanism.

To register a custom validation data type:

1. implement a component implementing the `ValidationDataType` interface or preferably the
   `AbstractValidationDataType` class (which provides some utility validation methods)
2. looks at the Javadoc of the `ValidationDataType` interface to get the list of
   methods to implement and some guides

The main choice to consider is about the _configuration data type_ (`C`) and the _data type_ (`T`).

The _data type_ is the type of the data you actually associate with a <<validation-runs-data,validation run>>. For
example, for some code coverage, it would be a percentage, and therefore represented as an `Int`. It could
be any other type, either complex or simple.

The _configuration data type_ is responsible for the configuration of the validation stamp, how the actual data
will be interpreted when it comes to computing a status. It could be one or several thresholds for example.

NOTE: The best thing to get started would be to copy the code of existing built-in data types.
