[[feeding-github]]
=== GitHub

There are several ways to integrate GitHub Actions workflows with Ontrack:

* ingestion of workflow data in Ontrack through a GitHub Webhook
* direct integration using GitHub Actions or the Ontrack CLI

[[feeding-github-ingestion]]
==== GitHub Ingestion Hook

Integration of Ontrack inside of <<feeding-github-actions,GitHub workflows>> is cumbersome and does not feel very natural.

A more seamless way to get GitHub workflows data into Ontrack is to work by ingesting the data directly from the workflow, without even adapting it.

We can do this by registering a webhook at the repository or organization level.

See <<integration-github-ingestion>> for the detailed configuration of the hook and all its options.

As a quick start:

1. Generate a unique token randomly (GitHub suggests using `ruby -rsecurerandom -e 'puts SecureRandom.hex(20)'` but any other method would do)
2. In the repository or organization, register a Webhook:
  * URL - `<ontrack>/hook/secured/github/ingestion`
  * Content type - `application/json`
  * Secret - the secret you generated in step (1)
  * Permissions:
    * Workflow jobs
    * Workflow runs
    * Pushes (for autoconfiguration)
3. In Ontrack, create at least one <<integration-github,GitHub configuration>>
4. Still in Ontrack, go to the _Settings > GitHub workflow ingestion_ section and set the token as generated in step (1)

From now on, everytime a working runs in GitHub, data about its steps will be created automatically in Ontrack.

[[feeding-github-actions]]
==== Ontrack CLI & GitHub Actions

You can easily use the <<feeding-cli,Ontrack CLI>> from your GitHub workflows by using the following actions:

* https://github.com/nemerosa/ontrack-github-actions-cli-setup[`nemerosa/ontrack-github-actions-cli-setup`] - install, configures and use the CLI to setup a project and branch in Ontrack based on GitHub information:

[source,yaml]
----
- name: Setup the CLI
  uses: nemerosa/ontrack-github-actions-cli-setup@v1
  with:
    github-token: ${{ github.token }}
    only-for: nemerosa
    url: <ontrack-url>
    token: ${{ secrets.ONTRACK_TOKEN }}
    config: github.com
    indexation: 120
----

===== Creating a build

https://github.com/nemerosa/ontrack-github-actions-cli-build[`nemerosa/ontrack-github-actions-cli-build`] - creates a build based on GitHub information:

[source,yaml]
----
- name: Ontrack build
  uses: nemerosa/ontrack-github-actions-cli-build@v1
----

and if you want to add some release information:

[source,yaml]
----
- name: Ontrack build
  uses: nemerosa/ontrack-github-actions-cli-build@v1
  with:
    release: ${{ env.VERSION }}
----

This steps:

* creates or updates the build
* sets the commit property
* sets the release property if provided
* sets some run info
* sets a link to the GH workflow

By default, the build name will be the workflow run number, you can change this by using the `build` input:

[source,yaml]
----
- name: Ontrack build
  uses: nemerosa/ontrack-github-actions-cli-build@v1
  with:
    build: <your build name>
----

===== Validating a build

* https://github.com/nemerosa/ontrack-github-actions-cli-validation[`nemerosa/ontrack-github-actions-cli-validation`] - creates a validation run for a build based on GitHub information:

[source,yaml]
----
- name: Ontrack build validation
  uses: nemerosa/ontrack-github-actions-cli-validation@main
  with:
    step-name: Ontrack build
    validation: BUILD
    build: ${{ github.run_number }}
    token: ${{ github.token }}
----

Note that when https://github.com/nemerosa/ontrack-github-actions-cli-setup[`nemerosa/ontrack-github-actions-cli-setup`] has been called into your workflow job, the <<feedback-cli,Ontrack CLI>> becomes available in all subsequent steps and be used directly:

[source,yaml]
----
- name: Setup the CLI
  uses: nemerosa/ontrack-github-actions-cli-setup@v1
  with:
    # ...
- name: Using the CLI
  run: ontrack-cli ...
----
