[[feeding-github]]
=== GitHub

There are several ways to integrate GitHub Actions workflows with Ontrack:

* ingestion of workflow data in Ontrack through a GitHub Webhook
* direct integration using GitHub Actions or the Ontrack CLI

[[feeding-github-ingestion]]
==== GitHub Ingestion Hook

Integration of Ontrack inside of <<feeding-github-actions,GitHub workflows>> is cumbersome and does not feel very natural.

A more seamless way to get GitHub workflows data into Ontrack is to work by ingesting the data directly from the workflow, without even adapting it.

We can do this by registering a webhook at the repository or organization level.

See <<integration-github-ingestion>> for the detailed configuration of the hook and all its options.

As a quick start:

1. Generate a unique token randomly (GitHub suggests using `ruby -rsecurerandom -e 'puts SecureRandom.hex(20)'` but any other method would do)
2. In the repository or organization, register a Webhook:
  * URL - `<ontrack>/hook/secured/github/ingestion`
  * Content type - `application/json`
  * Secret - the secret you generated in step (1)
  * Permissions:
    * Workflow jobs
    * Workflow runs
    * Pushes (for autoconfiguration)
3. In Ontrack, create at least one <<integration-github,GitHub configuration>>
4. Still in Ontrack, go to the _Settings > GitHub workflow ingestion_ section and set the token as generated in step (1)

From now on, everytime a working runs in GitHub, data about its steps will be created automatically in Ontrack.

[[feeding-github-actions]]
==== Ontrack CLI & GitHub Actions

You can easily use the <<feeding-cli,Ontrack CLI>> from your GitHub workflows by using the following actions:

* https://github.com/nemerosa/ontrack-github-actions-cli-setup[`nemerosa/ontrack-github-actions-cli-setup`] - install, configures and use the CLI to setup a project and branch in Ontrack based on GitHub information:

[source,yaml]
----
- name: Setup the CLI
  uses: nemerosa/ontrack-github-actions-cli-setup@v2
  with:
    github-token: ${{ github.token }}
    only-for: nemerosa
    url: <ontrack-url>
    token: ${{ secrets.ONTRACK_TOKEN }}
    config: github.com
    indexation: 120
----

===== Creating a build

https://github.com/nemerosa/ontrack-github-actions-cli-build[`nemerosa/ontrack-github-actions-cli-build`] - creates a build based on GitHub information:

[source,yaml]
----
- name: Ontrack build
  uses: nemerosa/ontrack-github-actions-cli-build@v1
----

and if you want to add some release information:

[source,yaml]
----
- name: Ontrack build
  uses: nemerosa/ontrack-github-actions-cli-build@v1
  with:
    release: ${{ env.VERSION }}
----

This steps:

* creates or updates the build
* sets the commit property
* sets the release property if provided
* sets some run info
* sets a link to the GH workflow

By default, the build name will be the workflow run number, you can change this by using the `build` input:

[source,yaml]
----
- name: Ontrack build
  uses: nemerosa/ontrack-github-actions-cli-build@v1
  with:
    build: <your build name>
----

===== Validating a build

* https://github.com/nemerosa/ontrack-github-actions-cli-validation[`nemerosa/ontrack-github-actions-cli-validation`] - creates a validation run for a build based on GitHub information:

[source,yaml]
----
- name: Ontrack build validation
  uses: nemerosa/ontrack-github-actions-cli-validation@main
  with:
    step-name: Ontrack build
    validation: BUILD
    build: ${{ github.run_number }}
    token: ${{ github.token }}
----

Note that when https://github.com/nemerosa/ontrack-github-actions-cli-setup[`nemerosa/ontrack-github-actions-cli-setup`] has been called into your workflow job, the https://github.com/nemerosa/ontrack-cli[Ontrack CLI] becomes available in all subsequent steps and be used directly:

[source,yaml]
----
- name: Setup the CLI
  uses: nemerosa/ontrack-github-actions-cli-setup@v1
  with:
    # ...
- name: Using the CLI
  run: ontrack-cli ...
----

[[feeding-github-actions-example]]
===== Example of GitHub pipeline with actions

In your repository or organization, start by declaring the following
elements:

* a `ONTRACK_URL` _variable_, having the URL of your Ontrack installation
* a `ONTRACK_TOKEN` _secret_, having an API token defined in Ontrack; the account linked to this token must have the necessary rights (typically administrator or automation)

In Ontrack itself, make sure to define at least one <<integration-github-config,GitHub configuration>>.

In each job, start by setting up the https://github.com/nemerosa/ontrack-cli[Ontrack CLI]:

[source,yaml]
----
- name: Setup the CLI
  uses: nemerosa/ontrack-github-actions-cli-setup@v2
  with:
    github-token: ${{ github.token }}
    url: ${{ vars.ONTRACK_URL }}
    token: ${{ secrets.ONTRACK_TOKEN }}
    config: github.com
    indexation: 60
----

NOTE: More options are available at https://github.com/nemerosa/ontrack-github-actions-cli-setup

Once this step has been run, the https://github.com/nemerosa/ontrack-cli[Ontrack CLI] is available in the
rest of the workflow.

Typically, you'll create a build in Ontrack:

[source,yaml]
----
  -  name: Ontrack build
     run: |
        ontrack-cli build setup \
          --project ${{ steps.ontrack.outputs.project }} \
          --branch ${{ steps.ontrack.outputs.branch }} \
          --build ${{ github.run_number }}
        ontrack-cli build set-property \
          --project ${{ steps.ontrack.outputs.project }} \
          --branch ${{ steps.ontrack.outputs.branch }} \
          --build ${{ github.run_number }} \
          git-commit \
          --commit ${{ github.sha }}
----

After the build is created, you can create some validations,
either using the https://github.com/nemerosa/ontrack-cli[Ontrack CLI]
or using the dedicated https://github.com/nemerosa/ontrack-github-actions-cli-validation[`ontrack-github-actions-cli-validation`] action.

For example:

[source,yaml]
----
  - uses: nemerosa/ontrack-github-actions-cli-validation@v2
    if: ${{ always() }}
----

NOTE: the `if: ${{ always() }}` is there to run this step even if the previous step is failed.

Using the CLI, it can look like:

[source,yaml]
----
  - name: Validation
    run: |
        ontrack-cli validate \
          --project ${{ steps.ontrack.outputs.project }} \
          --branch ${{ steps.ontrack.outputs.branch }} \
          --build ${{ github.run_number }} \
          --validation my-validation \
          --status PASSED
----

If you want to record some JUnit XML test results:

[source,yaml]
----
  - name: Validation
    if: ${{ always() }}
    run: |
        ontrack-cli validate \
          --project ${{ steps.ontrack.outputs.project }} \
          --branch ${{ steps.ontrack.outputs.branch }} \
          --build ${{ github.run_number }} \
          --validation my-validation \
          junit \
          --pattern "**/results/*.xml"
----

[[feeding-github-actions-promotions]]
===== Setting up validations and promotions

The https://github.com/nemerosa/ontrack-github-actions-cli-setup[`ontrack-github-actions-cli-setup`] action allows the setup of validations and promotions:

[source,yaml]
----
- name: Setup the CLI
  uses: nemerosa/ontrack-github-actions-cli-setup@v2
  with:
    # ...
    promotions: .github/ontrack/promotions.yaml
----

where `.github/ontrack/promotions.yaml` looks like:

[source,yaml]
----
BRONZE:
  validations:
    - BUILD
SILVER:
  validations:
    - ACCEPTANCE
  promotions:
    - BRONZE
----

This setup action does not allow much customization yet, and one
needs to rely on the https://github.com/nemerosa/ontrack-cli[Ontrack CLI] for more options (typing of the validations, auto-promotion, etc).

[[feeding-github-actions-auto-versioning]]
===== Setting up auto-versioning

TODO
