[[installation-package]]
=== Package installation

Ontrack provides installation packages for Debian & CentOS. Both
packages can be downloaded in the release page in GitHub:
https://github.com/nemerosa/ontrack/releases.

To run Ontrack, you need to make sure that the minimal <<installation-dependencies,dependencies>> are available:

* Postgres
* Elasticsearch

[[installation-rpm]]
==== RPM installation

To install Ontrack using RPM:

[source,bash]
----
rpm -i ontrack.rpm
----

The following directories are created:

|===
| Directory | Description

| `/opt/ontrack` | Binaries and scripts
| `/usr/lib/ontrack` | Working and <<configuration-properties,configuration>> directory
| `/var/log/ontrack` | Logging directory
|===

You can optionally create an `application.yml` configuration file in
`/usr/lib/ontrack`. For example, to customise the port Ontrack is running on:

[source,yaml]
----
server:
  port: 9080
----

Ontrack is installed as a service using `/etc/init.d/ontrack`.

[source,bash]
----
# Starting Ontrack
sudo service ontrack start
# Status of Ontrack
sudo service ontrack status
# Stopping Ontrack
sudo service ontrack stop
----

To upgrade Ontrack:

[source,bash]
----
# Stopping Ontrack
sudo service ontrack stop
# Updating
sudo rpm --upgrade ontrack.rpm
# Starting Ontrack
sudo service ontrack start
----

The optional `/etc/default/ontrack` file can be used to define
environment variables like
`JAVA_OPTIONS` or `SPRING_DATASOURCE_URL`.

For example:

[source]
./etc/default/ontrack
----
JAVA_OPTIONS=-Xmx2048m
SPRING_DATASOURCE_URL=jdbc:postgres://pg/ontrack
----

Other <<configuration-properties,Ontrack configuration properties>> can be
passed the same way.


[[installation-debian]]
==== Debian installation

To install Ontrack using Debian:

[source,bash]
----
dpkg -i ontrack.deb
----

The following directories are created:

|===
| Directory | Description

| `/opt/ontrack` | Binaries and scripts
| `/usr/lib/ontrack` | Working and <<configuration-properties,configuration>> directory
| `/var/log/ontrack` | Logging directory
|===

Ontrack is installed as a service using `/etc/init.d/ontrack`.

[source,bash]
----
# Starting Ontrack
sudo service ontrack start
# Status of Ontrack
sudo service ontrack status
# Stopping Ontrack
sudo service ontrack stop
----

The optional `/etc/default/ontrack` file can be used to define
environment variables like
`JAVA_OPTIONS` or `SPRING_DATASOURCE_URL`.

For example:

[source]
./etc/default/ontrack
----
JAVA_OPTIONS=-Xmx2048m
SPRING_DATASOURCE_URL=jdbc:postgres://pg/ontrack
----

Other <<configuration-properties,Ontrack configuration properties>> can be
passed the same way.
