[[installation-docker-compose]]
=== Docker Compose installation

The fastest way to start Ontrack is to use Docker Compose, but it might not be adapted for a production environment.

The Docker Compose file can be downloaded from:

https://github.com/nemerosa/ontrack/blob/{ontrack-version}/compose/docker-compose.yml

You can simply run it using:

[source,bash]
----
docker-compose up -d
----

This starts three services:

* Ontrack itself at http://localhost:8080
* a Postgres database
* an Elasticsearch single node

Neither Postgres or Elasticsearch are exposed by default, but you can of course edit the Docker Compose file at your convenience.

The version of Ontrack is set by default to `4` (latest 4.x version) but
you can override it using the `ONTRACK_VERSION` environment variable.

The memory settings and other JVM parameters for Ontrack can be passed
using the `JAVA_OPTIONS` environment variable, which defaults to
`-Xms1024m -Xmx1024m`.

Other <<configuration-properties,Ontrack configuration properties>> must be passed
through environment variables.

Three named Docker volumes are created for the data to be persisted:

* `ontrack_postgres`
* `ontrack_elasticsearch`
* `ontrack_data`

For other volume configuration, please edit the Docker Compose file.
