[[installation-dependencies]]
=== Installation dependencies

Ontrack relies on the following components to be available:

* Postgres - for storage of information
* Elasticsearch - for search indexation

[[installation-postgres]]
==== Postgres

Versions 9.5.+ and version 10.+ of Ontrack have been tested.

By default, Ontrack will use the following
<<configuration-properties,configuration properties>> and their default
values to connect to Postgres:

|===
| Property | Description | Default value

| spring.datasource.url | JDBC URL to the Postgres Ontrack DB | `jdbc:postgresql://localhost/ontrack`
| spring.datasource.username | Username used to connect to the Postgres Ontrack DB | `ontrack`
| spring.datasource.password | Password used to connect to the Postgres Ontrack DB | `ontrack`
|===

Other properties are available in link:https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/html/appendix-application-properties.html#data-properties[Spring Boot].

[[installation-elasticsearch]]
==== Elasticsearch

Version 7.5.+ has been tested.

By default, Ontrack will use the following
<<configuration-properties,configuration properties>> and their default
values to connect to Postgres:

|===
| Property | Description | Default value

| spring.elasticsearch.rest.uris | REST URI of Elasticsearch | `http://localhost:9200`
|===

Other properties are available in link:https://docs.spring.io/spring-boot/docs/{spring-boot-version}/reference/html/appendix-application-properties.html#data-properties[Spring Boot].
