[[installation]]
== Installation

There are several ways to install Ontrack.

[[installation-docker]]
=== Installing using Docker

Ontrack is distributed as a Docker image on the https://hub.docker.com[Docker Hub], as `nemerosa/ontrack:{ontrack-version}`.

[[installation-docker-overview]]
==== Overview

The Ontrack image exposes the ports `443` and `8080`.

Two volumes are defined:

* `/var/ontrack/data` - contains the data for Ontrack (files & database) but also the log files. This is typically provided through a data volume container.
* `/var/ontrack/conf` - contains the configuration files for Ontrack (see later).

[[installation-docker-basic]]
==== Basic deployment

You can start Ontrack as a container and a shared database and configuration on the host using:

[source,bash]
----
docker run --detach \
   --publish=8080:8080 \
   --volume=/var/ontrack/data:/var/ontrack/data \
   --volume=/var/ontrack/conf:/var/ontrack/conf \
   nemerosa/ontrack
----

The configuration files for Ontrack can be put on the host in
`/var/ontrack/conf` and the database and working files will be available
in `/var/ontrack/data`. The application will be available on port `8080` of
the host.

[[installation-docker-compose]]
==== Using compose to deploy Ontrack using HTTPS and Grafana/InfluxDB for metrics

You can use http://docs.docker.com/compose[Docker Compose] to deploy Ontrack
running on HTTPS and having its metrics exported to
<<monitoring, InfluxDB>>, and exposed through a Grafana dashboard.

Gets the source code from https://github.com/nemerosa/ontrack/tree/master/gradle/compose[GitHub].

[[installation-docker-compose-preparation]]
===== Preparation

In the `prod/ontrack` folder, put two files:

* an `application-prod.yml` file:

[source,yaml]
----
# Production environment
server:
  ssl:
     key-alias: server
     key-store: "config/ontrack_your_domain.jks"
     key-store-password: "your store password"
----

* a `ontrack_your_domain.jks` file which contains the SSL certificate for your
web site serving Ontrack. See this
https://nemerosa.ghost.io/2015/07/25/enabling-ssl-with-spring-boot-going-real[blog entry]
to know how to create it.

WARNING: Never store those two files in a SCM

[[installation-docker-compose-host]]
===== Docker host configuration

Prepare the Docker host to have its Ontrack configuration. If you are using the
http://docs.docker.com/machine[Docker Machine] `ontrack-production`:

[source,bash]
----
docker-machine ssh ontrack-production rm -rf /var/ontrack/conf
docker-machine scp -r \
   prod/ontrack \
   ontrack-production:/var/ontrack/conf
----

This copies the content of the `prod/ontrack` folder (three files:
`application.yml`, `application-prod.yml` and the `.jks` file) into the
`/var/ontrack/conf` directory of the Docker host.

[[installation-docker-compose-launching]]
===== Launching the composition

When done, you just have to run Docker Compose:

[source,bash]
----
ONTRACK_VERSION=2.16.7 docker-compose \
    -f docker-compose.yml -f docker-compose-prod.yml \
    --project-name prod \
    --forceRecreate
----

This will install:

* the versison `2.16.7` of Ontrack in a container
* a Grafana container
* an InfluxDB container

The Ontrack container is configured to send its metrics to the InfluxDB
container, and the Grafana application is configured to access
the same InfluxDB database.

Ontrack is accessible using `https`, using the default `443` port.

Grafana is accessible on port `3000` and the default `admin` password
is `admin` and should be changed immediately.

[[installation-rpm]]
=== RPM installation

[[installation-debian]]
=== Debian installation

You can install Ontrack using a Debian file (`.deb`) you can download from the
https://github.com/nemerosa/ontrack/releases[releases] page.

To install Ontrack:

[source,bash]
----
dpkg -i ontrack.deb
----

The following directories are created:

|===
| Directory | Description

| `/opt/ontrack` | Binaries and scripts
| `/usr/lib/ontrack` | Working directory
| `/var/log/ontrack` | Logging directory
|===

Ontrack is installed as a service using `/etc/init.d/ontrack`.

[source,bash]
----
# Starting Ontrack
service ontrack start
# Status of Ontrack
service ontrack status
# Stopping Ontrack
service ontrack stop
----

[[installation-digitalocean]]
=== Installing at DigitalOcean

[[installation-dockercloud]]
=== Installing on Docker Cloud

[[installation-sa]]
=== Standalone installation
