[[installation]]
== Installation

There are several ways to install Ontrack.

[[installation-prerequisites]]
=== Prerequisites

Ontrack has been tested on different Linux variants (Ubuntu, Debian, CentOS)
and should also work on Windows.

Ontrack relies on at least a JDK 8 build 25. More recent versions of the JDK8
are OK. However, no test has been done yet using early JDK 9 versions.

Ontrack runs fine with 512 Mb of memory. However, think of upgrading to 2 Gb of
memory if you intend to host a lot of projects. See the different installation
modes (Docker, RPM, etc.) to know how to setup the memory settings.

Ontrack stores its data in a Postgres database.

[[installation-quick-start]]
=== Quick start

The fastest way to start Ontrack is to use <<installation-docker-compose,Docker Compose>>.

[[installation-postgres]]
=== Postgres database

Unless you choose to deploy with <<installation-docker-compose,Docker Compose>>,
you will need to have a Postgres database accessible by Ontrack.

Version 9.5 of Postgres has been tested successfully with Ontrack, but
any later 9.x version should be OK as well.

No test with Postgres 10.x has been performed yet.

Ontrack will by default try to connect to
`jdbc:postgresql://postgresql/ontrack`, using `ontrack / ontrack`
as credentials.

Those parameters can be configured using normal Spring Boot JDBC <<configuration,configuration>>,
for example using arguments at startup:

[source]
----
--spring.datasource.url=jdbc:postgresql://localhost:5432/ontrack
--spring.datasource.username=myuser
--spring.datasource.password=password
----

See the https://docs.spring.io/spring-boot/docs/1.5.8.RELEASE/reference/htmlsingle/#boot-features-external-config[Spring Boot documentation]
to see other and better ways to pass
those <<configuration,configuration>> parameters.

[[installation-docker]]
=== Installing using Docker

Ontrack is distributed as a Docker image on the https://hub.docker.com[Docker Hub], as `nemerosa/ontrack:{ontrack-version}`.

[[installation-docker-overview]]
==== Overview

The Ontrack image exposes the ports `443` and `8080`.

Two volumes are defined:

* `/var/ontrack/data` - contains some working files but also the log files.
* `/var/ontrack/conf` - contains the <<configuration-properties,configuration files>> for Ontrack (see later).

[[installation-docker-basic]]
==== Basic deployment

You can start Ontrack as a container and a shared database and configuration on the host using:

[source,bash]
----
docker run --detach \
   --publish=8080:8080 \
   --volume=/var/ontrack/data:/var/ontrack/data \
   --volume=/var/ontrack/conf:/var/ontrack/conf \
   nemerosa/ontrack
----

The <<configuration,configuration files>> for Ontrack can be put on the host in
`/var/ontrack/conf` and the database and working files will be available
in `/var/ontrack/data`. The application will be available on port `8080` of
the host.

Java options, like memory settings, can be passed to the Docker container using
the `JAVA_OPTIONS` environment variable:

[source,bash]
----
docker run \
   ...
   --env "JAVA_OPTIONS=-Xmx2048m" \
   ...
----

[[installation-docker-compose]]
==== Docker Compose deployment

Create the following file:

[source,yaml]
.docker-compose.yml
----
version: "2.1"

services:
  # Ontrack container
  ontrack:
    image: nemerosa/ontrack:3
    environment:
        PROFILE: prod
    links:
      - "postgresql:postgresql"

  # Postgresql database
  postgresql:
    image: postgres:9.5.2
    environment:
      POSTGRES_DB      : ontrack
      POSTGRES_USER    : ontrack
      POSTGRES_PASSWORD: ontrack
    ports:
      - "5432"

----

[[installation-rpm]]
=== RPM installation

You can install Ontrack using a RPM file you can download from the
https://github.com/nemerosa/ontrack/releases[releases] page.

The RPM is continuously tested on CentOS 6.7 and CentOS 7.1.

To install Ontrack:

[source,bash]
----
rpm -i ontrack.rpm
----

The following directories are created:

|===
| Directory | Description

| `/opt/ontrack` | Binaries and scripts
| `/usr/lib/ontrack` | Working and <<configuration-properties,configuration>> directory
| `/var/log/ontrack` | Logging directory
|===

You can optionally create an `application.yml` configuration file in
`/usr/lib/ontrack`. For example, to customise the port Ontrack is running on:

[source,yaml]
----
server:
  port: 9080
----

Ontrack is installed as a service using `/etc/init.d/ontrack`.

[source,bash]
----
# Starting Ontrack
service ontrack start
# Status of Ontrack
service ontrack status
# Stopping Ontrack
service ontrack stop
----

To upgrade Ontrack:

[source,bash]
----
# Stopping Ontrack
sudo service ontrack stop
# Updating
sudo rpm --upgrade ontrack.rpm
# Starting Ontrack
sudo service ontrack start
----

The optional `/etc/default/ontrack` file can be used to define the
`JAVA_OPTIONS`, for example:

[source]
./etc/default/ontrack
----
JAVA_OPTIONS=-Xmx2048m
----

[[installation-debian]]
=== Debian installation

You can install Ontrack using a Debian file (`.deb`) you can download from the
https://github.com/nemerosa/ontrack/releases[releases] page.

To install Ontrack:

[source,bash]
----
dpkg -i ontrack.deb
----

The following directories are created:

|===
| Directory | Description

| `/opt/ontrack` | Binaries and scripts
| `/usr/lib/ontrack` | Working and <<configuration-properties,configuration>> directory
| `/var/log/ontrack` | Logging directory
|===

Ontrack is installed as a service using `/etc/init.d/ontrack`.

[source,bash]
----
# Starting Ontrack
service ontrack start
# Status of Ontrack
service ontrack status
# Stopping Ontrack
service ontrack stop
----

The optional `/etc/default/ontrack` file can be used to define the
`JAVA_OPTIONS`, for example:

[source]
./etc/default/ontrack
----
JAVA_OPTIONS=-Xmx2048m
----

[[installation-sa]]
=== Standalone installation

Ontrack can be downloaded as a JAR and started as a Spring Boot application.

Download the JAR from the
https://github.com/nemerosa/ontrack/releases[Ontrack release page]

Start it using `java -jar ontrack.jar` with the following options:

* `--spring.datasource.url=jdbc:h2:/var/ontrack/data/database/data`
* or `--spring.datasource.url=jdbc:h2:./database/data`
* and any other Java option, like memory settings: `-Xmx2048m`
* or <<configuration,configuration parameter>> like `--server.port=9999`

to specify the location of the H2 database files.

<<configuration-properties,Options>> can also be specified in an `application.yml` file in
the working directory.

For example:

[source,yaml]
.application.yml
----
spring:
   datasource:
      url: "jdbc:h2:/var/ontrack/data/database/data"
----

[[configuration]]
=== Configuration

As a regular http://projects.spring.io/spring-boot/[Spring Boot application],
Ontrack can be configured using system properties and/or property files and/or
YAML files. See the
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-properties-and-configuration[Spring Boot documentation]
for more details.

NOTE: The way to provide a YAML `application.yml` configuration file or
command line arguments will vary
according to the installation (Docker, RPM, etc.). See the corresponding
section above for more details.

For example, to setup the port Ontrack is running on, you can use the
`server.port` property. Using a YAML file:

[source,yaml]
.application.yml
----
server.port=9999
----

or the command line option:

[source,bash]
----
--server.port=9999
----

See <<configuration-properties>> for the list of all available properties.
