[[integration-encryption]]
=== Encryption service

Secrets used by Ontrack are <<architecture-encryption,encrypted>> using keys
managed by a `ConfidentialStore`.

Ontrack provides three types of storage:

* file based storage (default)
* https://www.vaultproject.io/[Vault] storage
* database storage

If needed, you can also create your own form of storage using
<<extension-encryption,extensions>>.

[[integration-encryption-selection]]
==== Selection of the confidential store

The selection of the confidential store is done at startup time using the
`ontrack.config.key-store`
<<configuration-properties,configuration property>>.

It defaults to `file` (see below).

Additional configuration properties might be needed according to the type of
store.

[[integration-encryption-file]]
==== File confidential store

This is the default store but its selection can be made explicit by setting
the `ontrack.config.key-store`
<<configuration-properties,configuration property>> to `file`.

This store will store the keys in the
<<configuration-properties,working directory>> under the
`security/secrets` subfolder.

A `master.key` file is used to encrypt the individual keys themselves, so
two files will be typically present:

* `master.key`
* `net.nemerosa.ontrack.security.EncryptionServiceImpl.encryption`

[[integration-encryption-jdbc]]
==== JDBC confidential store

TODO

[[integration-encryption-vault]]
==== Vault confidential store

TODO

[[integration-encryption-migration]]
==== Migrating encryption keys

TODO

[[integration-encryption-lost]]
==== Losing the encryption keys

TODO
