[[monitoring]]
=== Monitoring

Ontrack is based on http://projects.spring.io/spring-boot[Spring Boot] and
exports metrics and health indicators that can be used to monitor the status
of the applications.

[[monitoring-health]]
==== Health

The `/manage/health` end point provides a JSON tree which indicates the status
of all connected systems: JIRA, Jenkins, Git
repositories, etc.

Note than an administrator can have access to this information as a dashboard
in the _Admin console_ (accessible through the user menu).

[[monitoring-metrics]]
==== Metrics

[WARNING]
====
Since version 2.35 / 3.35, Ontrack uses the http://micrometer.io/[Micrometer]
framework to manage metrics, in order to allow a better integration with
http://projects.spring.io/spring-boot/[Spring Boot 2].

See <<appendix-metrics-migration>> for information about the migration.
====

See <<operations-metrics>> for the different options for the metrics backends.

[[monitoring-metrics-list]]
===== List of metrics

[NOTE]
====
The list of Ontrack specific metrics and their tags and values is available
using the `/manage/ontrack_metrics` endpoint. Note that this endpoint
needs authentication and some <<security,administrator privileges>>.
====

General metrics:

* `ontrack_error` (counter) - number of error (the `type` tag contains the
  type of error)

Statistics about the <<model,objects>> stored by Ontrack:

* `ontrack_entity_project_total` (gauge) - total number of projects
* `ontrack_entity_branch_total` (gauge) - total number of branches
* `ontrack_entity_build_total` (gauge) - total number of builds
* `ontrack_entity_promotionLevel_total` (gauge) - total number of promotion levels
* `ontrack_entity_promotionRun_total` (gauge) - total number of promotion runs
* `ontrack_entity_validationStamp_total` (gauge) - total number of validation stamps
* `ontrack_entity_validationRun_total` (gauge) - total number of validation runs
* `ontrack_entity_validationRunStatus_total` (gauge) - total number of validation run statuses
* `ontrack_entity_property_total` (gauge) - total number of properties
* `ontrack_entity_event_total` (gauge) - total number of events

General metrics about <<architecture-jobs,jobs>>:

* `ontrack_job_count_total` (gauge) - total number of jobs
* `ontrack_job_running_total` (gauge) - total number of running jobs
* `ontrack_job_error_total` (gauge) - total number of jobs in error
* `ontrack_job_timeout_total` (gauge) - total number of jobs in timeout
* `ontrack_job_paused_total` (gauge) - total number of paused jobs
* `ontrack_job_disabled_total` (gauge) - total number of disabled jobs
* `ontrack_job_invalid_total` (gauge) - total number of invalid jobs
* `ontrack_job_error_count_total` (gauge) - total number of errors among all the jobs
* `ontrack_job_timeout_count_total` (gauge) - total number of timeouts among all the jobs

Information about individual jobs:

* `ontrack_job_duration_ms` (timer) - duration of the execution of the job
* `ontrack_job_run_count` (counter) - number of times a job has run
* `ontrack_job_errors` (counter) - number of errors for this job

[NOTE]
====
Job metrics have the following tags:

* `job-category` - category of the job
* `job-type` - type of the job
====

Run information:

* `ontrack_run_build_time_seconds` (timer) - duration of a run for a build.
  It is associated with `project` and `branch` tags.
* `ontrack_run_validation_run_time_seconds` (timer) - duration of a run for a
  validation run. It is associated with `project`, `branch`, `validation_stamp`
  and `status` tags.

More details at <<run-info>>.

Information about connectors (Jenkins, JIRA, Git, etc.):

* `ontrack_connector_count` (gauge) - number of connectors
* `ontrack_connector_up` (gauge) - number of UP connectors
* `ontrack_connector_down` (gauge) - number of DOWN connectors

[NOTE]
====
Connector metrics have the following tags:

* `type` - type of connector (like `jenkins`, `jira`, ...)
====

Information about the execution times of event listeners:

* `ontrack_event_listener_time` (timer) - duration for the synchronous processing of an event on the backend. The `eventListener` tag contains the FQCN of the event listener service.

Information about the connectivity of remote Git operations:

* `ontrack_git_connect_retries` - Number of retries on connection errors
* `ontrack_git_connect_errors` -Number of terminal connection errors

Information about the delivery, see <<delivery-metrics>>.
