[[integration-bitbucket-cloud]]
=== Working with Bitbucket Cloud

https://bitbucket.org[Bitbucket Cloud] is an enterprise SaaS Git
repository manager by Atlassian.

When working with Git in Ontrack, one can configure a project
to connect to a Git repository defined in Bitbucket Cloud.

[[integration-bitbucket-cloud-config]]
==== General configuration

The access to a Bitbucket Cloud _workspace_ must be configured.

[NOTE]
====
The access to Bitbucket Cloud from Ontrack is configured at Bitbucket Cloud _workspace_ level. If your Ontrack instance uses several workspaces, you can define several Bitbucket Cloud configurations, one per workspace.
====

1. as <<security,administrator>>, go to the _Bitbucket Cloud configurations_ menu
2. click on _Create a configuration_
3. in the configuration dialog, enter the following parameters:
** **Name**  - unique name for the configuration
** **Workspace** - name of the Bitbucket Cloud workspace to use
** **User** & **Password** - credentials used to access Bitbucket Cloud. The password must be a https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/[Bitbucket Cloud app password].

[NOTE]
====
The app password must be granted at least the following rights:

* project > read
* repository > read
* pull requests > read
* issues > read
====

The existing configurations can be updated and deleted.

[[integration-bitbucket-cloud-config-casc]]
===== Configuration as Code

You can use <<casc,configuration as code>> to configure the Bitbucket Cloud configurations. For example:

[source,yaml]
----
ontrack:
  config:
    bitbucket-cloud:
      - name: my-config
        workspace: my-workspace
        user: my-user
        password: <app password>
----

[[integration-bitbucket-cloud-project]]
==== Project configuration

The link between a project and a Bitbucket Cloud repository is defined by the _Bitbucket Cloud configuration_ property:

* **Configuration** - selection of the Bitbucket Cloud configuration created before
* **Repository** - name of the Bitbucket Cloud repository
** Indexation interval - interval (in minutes) between each synchronization
(Ontrack maintains internally a clone of the Bitbucket Cloud repositories)
** Issue configuration - <<usage-issues,configured issue service>> to use
when looking for issues in commits.

Branches can be <<usage-git,configured for Git>> independently.
