[[run-info]]
=== Run info

<<builds,Builds>> and <<validation-runs,validation runs>> can be associated with some _run information_ which contains:

* source of the information, like a Jenkins job
* trigger of the information, like a SCM change
* duration of the collection for the information (like the duration of a job)

[[run-info-collection]]
==== Collection of run info

Run info can be attached to a build or a validation run using the REST API or the DSL of Ontrack.

This is typically done at CI engine level, where a solution like the
https://plugins.jenkins.io/ontrack[Ontrack Jenkins plugin] simplifies the operation.

When using the Jenkins pipeline as code, the `ontrackBuild` and `ontrackValidate` steps will do this
automatically, so nothing to change. For example:

[source,groovy]
----
post {
   success {
       ontrackBuild project: "xxx", branch: "1.0", build: version
   }
}
----

When using the DSL, the run info must be specified explicitly. The Jenkins plugin provides a `jenkins.runInfo`
binding which contains some run into ready to be passed:

[source,groovy]
----
ontrackScript script: """
    def b = ontrack.build(...)
    b.runInfo = jenkins.runInfo
    """
----

[[run-info-displaying]]
==== Displaying the run info

The run info is displayed in the branch overview and the build page for builds, and in the validation stamp
and the validation run pages for the validation runs.

It is of course available through the REST API, GraphQL and the DSL.

[[run-info-export]]
==== Exporting the run info

While the run info is available from Ontrack, it can also be exported to
other databases.

As of today, only InfluxDB is supported.

[[run-info-export-influxdb]]
===== Exporting the run info to InfluxDB

[NOTE]
====
InfluxDB connector must be enabled - see <<monitoring-metrics-influxdb>>.
====

In order to export Ontrack run info as points into an InfluxDB database,
following elements must be configured:

|===
| Property | Environment variable | Default | Description

| `ontrack.influxdb.run-info`
| `ONTRACK_INFLUXDB_RUN_INFO`
| `true`
| If `true`, the run info is exported to InfluxDB (`true` by default)

|===

[[run-info-export-extending]]
===== Exporting the run info using extensions

It's possible to manage your own export of run info by creating a `RunInfoListener` component.

See <<extending-metrics-run-info-listeners>> for more information.
