@startuml

start

group Receiving

    :Event received;
    :Event pushed on listening queue;

end group

#palegreen:Listening queue;

group Listening

    :Event removed from the listening queue;
    :Getting all subscriptions for this event;

    group For each subscription

        :Event pushed on dispatching queue;

    end group

end group

#palegreen:Dispatching queue;

group Dispatching

    :Event removed from the dispatching queue;
    :Publication to the channel;

end group

end

@enduml