@startuml

actor Client
participant InfluxDBConnection
participant InfluxDB
database "Remote InfluxDB" as Remote

== First time connection ==

Client -> InfluxDBConnection: current
note right: Get the current ""InfluxDB"" connection

InfluxDBConnection -> InfluxDB: get current connection
InfluxDB --> InfluxDBConnection: ""null""

group Write lock
    InfluxDBConnection -> InfluxDB: create connection
    InfluxDB --> InfluxDBConnection: current connection
end

InfluxDBConnection --> Client: current connection

== Connection with check OK ==

Client -> InfluxDBConnection: current
note right: Get the current ""InfluxDB"" connection

InfluxDBConnection -> InfluxDB: get current connection
InfluxDB --> InfluxDBConnection: current connection

group Read lock
    InfluxDBConnection -> InfluxDB: checks connection
    InfluxDB -> Remote: checks connection
    Remote --> InfluxDB: connection OK
    InfluxDB --> InfluxDBConnection: connection OK
end

InfluxDBConnection --> Client: current connection

== Connection with check not OK ==

Client -> InfluxDBConnection: current
note right: Get the current ""InfluxDB"" connection

InfluxDBConnection -> InfluxDB: get current connection
InfluxDB --> InfluxDBConnection: current connection

group Read lock
    InfluxDBConnection -> InfluxDB: checks connection
    InfluxDB -> Remote: checks connection
    Remote --> InfluxDB: connection NOT OK
    InfluxDB --> InfluxDBConnection: connection NOT OK
end

group Write lock
    InfluxDBConnection -> InfluxDB: create connection
    InfluxDB --> InfluxDBConnection: current connection
end

InfluxDBConnection --> Client: current connection

@enduml