@startuml

actor Configurator

box "CI"
    control CI
end box

box "Ontrack"
    participant Project
    participant Build
    control "SonarQube extension" as SonarQubeJob
end box

box "SonarQube"
    database Project as SonarQubeProject
end box

database InfluxDB

== Configuration ==

Configurator -> Project: Configures SonarQube project
Project <--> SonarQubeProject: association

== Scanning ==

CI -> Build: a build is created by the CI process
CI -> SonarQubeProject: a scan is performed for the same build
note right
    Build identification is based on either the name of the build
    or its label.
end note
CI -> Build: creates a validation run for the scan
Build -> SonarQubeJob: this triggers the collection of measures
SonarQubeJob -> SonarQubeProject: gets the list of measures for this build
SonarQubeProject --> SonarQubeJob: measures
SonarQubeJob -> Build: stores the measures
SonarQubeJob -> InfluxDB: stores the measures

@enduml