[[monitoring]]
=== Monitoring

Ontrack is based on http://projects.spring.io/spring-boot[Spring Boot] and
exports metrics and health indicators that can be used to monitor the status
of the applications.

[[monitoring-health]]
==== Health

The `/manage/health` end point provides a JSON tree which indicates the status
of all connected systems: JIRA, Jenkins, Subversion repositories, Git
repositories, etc.

Note than an administrator can have access to this information as a dashboard
in the _Admin console_ (accessible through the user menu).

[[monitoring-metrics]]
==== Metrics

[WARNING]
====
Since version 2.35 / 3.35, Ontrack uses the http://micrometer.io/[Micrometer]
framework to manage metrics, in order to allow a better integration with
http://projects.spring.io/spring-boot/[Spring Boot 2].

See <<appendix-metrics-migration>> for information about the migration.
====

By default, Ontrack supports two external registries for metrics:

* InfluxDB
* Prometheus

The export to those engine is _disabled_ by default and must be enabled
explicitely.

For example, for Prometheus, you can use the
`management.metrics.export.prometheus.enabled` property or
the `MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED` environment variable.

For the rest of the configuration, you have to consult the
Spring Boot or Micrometer documentation.

[[monitoring-metrics-list]]
===== List of metrics

[NOTE]
====
The list of Ontrack specific metrics and their tags and values is available
using the `/manage/ontrack_metrics` endpoint. Note that this endpoint
needs authentication and some <<security,administrator privileges>>.
====

General metrics:

* `ontrack_error` (counter) - number of error (the `type` tag contains the
  type of error)

Statistics about the <<model,objects>> stored by Ontrack:

* `ontrack_entity_project_total` (gauge) - total number of projects
* `ontrack_entity_branch_total` (gauge) - total number of branches
* `ontrack_entity_build_total` (gauge) - total number of builds
* `ontrack_entity_promotionLevel_total` (gauge) - total number of promotion levels
* `ontrack_entity_promotionRun_total` (gauge) - total number of promotion runs
* `ontrack_entity_validationStamp_total` (gauge) - total number of validation stamps
* `ontrack_entity_validationRun_total` (gauge) - total number of validation runs
* `ontrack_entity_validationRunStatus_total` (gauge) - total number of validation run statuses
* `ontrack_entity_property_total` (gauge) - total number of properties
* `ontrack_entity_event_total` (gauge) - total number of events

General metrics about <<architecture-jobs,jobs>>:

* `ontrack_job_count_total` (gauge) - total number of jobs
* `ontrack_job_running_total` (gauge) - total number of running jobs
* `ontrack_job_error_total` (gauge) - total number of jobs in error
* `ontrack_job_paused_total` (gauge) - total number of paused jobs
* `ontrack_job_disabled_total` (gauge) - total number of disabled jobs
* `ontrack_job_invalid_total` (gauge) - total number of invalid jobs
* `ontrack_job_error_count_total` (gauge) - total number of errors among all the jobs

Information about individual jobs:

* `ontrack_job_duration_ms` (timer) - duration of the execution of the job
* `ontrack_job_run_count` (counter) - number of times a job has run
* `ontrack_job_errors` (counter) - number of errors for this job

[NOTE]
====
Job metrics have the following tags:

* `job-category` - category of the job
* `job-type` - type of the job
* `job-id` - ID of the job
====

Run information:

* `ontrack_run_build_time_seconds` (timer) - duration of a run for a build.
  It is associated with `project` and `branch` tags.
* `ontrack_run_validation_run_time_seconds` (timer) - duration of a run for a
  validation run. It is associated with `project`, `branch`, `validation_stamp`
  and `status` tags.

More details at <<run-info>>.

Information about connectors (Jenkins, JIRA, Git, etc.):

* `ontrack_connector_count` (gauge) - number of connectors
* `ontrack_connector_up` (gauge) - number of UP connectors
* `ontrack_connector_down` (gauge) - number of DOWN connectors

[NOTE]
====
Connector metrics have the following tags:

* `type` - type of connector (like `jenkins`, `jira`, ...)
====

[[monitoring-metrics-influxdb]]
===== InfluxDB metrics

[WARNING]
====
This is an experimental feature. In the future, especially when migrating
to Spring Boot 2.0, the configuration might change. The feature is very likely
to stay though.
====

The InfluxDB <<extending,extension>> is shipped by default with Ontrack
but is activated only if some properties are correctly set:

|===
| Property | Environment variable | Default | Description

| `ontrack.influxdb.enabled`
| `ONTRACK_INFLUXDB_ENABLED`
| `false`
| Enables the export of run info to InfluxDB

| `ontrack.influxdb.uri`
| `ONTRACK_INFLUXDB_URI`
| "http://localhost:8086"
| URI of the InfluxDB database
|===

Optionally, the following properties can also be set:

|===
| Property | Environment variable | Default | Description

| `ontrack.influxdb.username`
| `ONTRACK_INFLUXDB_USERNAME`
| "root"
| User name to connect to the InfluxDB database

| `ontrack.influxdb.password`
| `ONTRACK_INFLUXDB_PASSWORD`
| "root"
| Password to connect to the InfluxDB database

| `ontrack.influxdb.db`
| `ONTRACK_INFLUXDB_DB`
| "ontrack"
| Name of the InfluxDB database

| `ontrack.influxdb.create`
| `ONTRACK_INFLUXDB_CREATE`
| `true`
| If `true`, the database is created at startup

| `ontrack.influxdb.ssl.host-check`
| `ONTRACK_INFLUXDB_SSL_HOST_CHECK`
| `true`
| If `false`, disables host checking for certificates. *This should not be
  used for a production system!*

| `ontrack.influxdb.log`
| `ONTRACK_INFLUXDB_LOG`
| `NONE`
| Level of log when communicating with InfluxDB. Possible values are: `NONE`, `BASIC`, `HEADERS` and `FULL`
|===

When an InfluxDB connector is correctly set, some Ontrack information
is automatically sent to create timed values:

* <<run-info-export-influxdb,run info>>
* <<validation-runs-data-metrics,validation run data>>
