@startuml

actor Client
note left of Client
    Any remote client
    of Ontrack
end note

component "kdsl-connector" as Connector <<jar>>
note right of Connector
    HTTP layer for connecting to
    a remote Ontrack instance
end note

component "kdsl-spec" as Spec <<api>>
note bottom of Spec
    Transport-independent specification
    for the Ontrack KDSL
end note

component "kdsl-http" as HTTP <<jar>>
note top of HTTP
    Implementation of the KDSL
    based on a HTTP connector
end note

component "rest/graphql" as UI <<core>>
note bottom of UI
    Ontrack UI end points
    (REST & GraphQL)
end note

HTTP --|> Spec
HTTP --> Connector

Connector ..> UI: maps to

Client --|> HTTP

@enduml