@startuml

component "kdsl-connector" as Connector <<jar>>

component "kdsl-spec" as Spec <<api>>

component "kdsl-http" as HTTP <<jar>>

component "rest/graphql" as UI <<core>>

HTTP --|> Spec
HTTP --> Connector
Connector ..> UI: maps to

package "ontrack-extension-xxx" {
    component "src/kdsl" as ExtensionDSL

    ExtensionDSL --> HTTP
}

@enduml