[[ldap]]
=== LDAP setup

It is possible to enable authentication using a LDAP instance and to use the
LDAP-defined groups to map them against Ontrack groups.

[[ldap-setup]]
==== LDAP general setup

As an _administrator_, go to the _Settings_ menu. In the _LDAP settings_
section, click on _Edit_ and fill the following parameters:

* _Enable LDAP authentication_: Yes
* _URL_: URL to your LDAP
* _User_ and _Password_: credentials needed to access the LDAP
* _Search base_: query to get the user
* _Search filter_: filter on the user query
* _Full name attribute_: attribute which contains the full name, `cn` by
  default
* _Email attribute_: attribute which contains the email, `email` by default
* _Group attribute_: attribute which contains the list of groups a user belongs
  to, `memberOf` by default
* _Group filter_: optional, name of the OU field used to filter groups a user
  belongs to

IMPORTANT: As of version 2.14, the list of groups (indicated by the `memberOf`
      attribute or any other attribute defined by the _Group attribute_
      property) is not searched recursively and that only the direct groups
      are taken into account.

[[ldap-mapping]]
==== LDAP group mapping

A LDAP group a user belongs to can be used to map onto an Ontrack group.

As an _administrator_, go to the _Account management_ menu and click on the
_LDAP mapping_ command.

NOTE: This command is only available if the LDAP authentication has been
enabled in the general settings.

To add a new mapping, click on _Create mapping_ and enter:

* the _name_ of the LDAP group you want to map
* the Ontrack _group_ which must be mapped

For example, if you map the `ontrack_admin` LDAP group to an _Administrators_
group in Ontrack, any user who belongs to _ontrack_admin_  will automatically
be assigned to the _Administrators_ group when connecting.

NOTE: This assignment based on mapping is dynamic only, and no information is
stored about it in Ontrack.

Note that those LDAP mappings can be generated using the DSL.

Existing mappings can be updated and deleted.
