@startuml
component [client]
component [common]
component [extension-api]
component [extension-support]
component [job]
component [json]
component [model]
component [repository]
component [repository-impl]
component [repository-support]
component [service]
component [ui]
component [ui-support]
component [web]

[client] --> [common]
[client] --> [json]

[extension-api] --> [model]

[extension-support] --> [client]
[extension-support] --> [ui-support]

[job] --> [common]

[model] --> [json]
[model] --> [job]

[repository] --> [model]

[repository-impl] --> [repository]
[repository-impl] --> [repository-support]

[repository-support] --> [model]

[service] --> [repository]
[service] --> [extension-api]

[ui] --> [extension-support]
[ui] --> [service]
[ui] --> [repository-impl]
[ui] --> [web]

[ui-support] --> [extension-api]

@enduml
