[[searching]]
=== Searching

The top search box allows to search objects stored in Ontrack like
projects, branches or builds, based on their names or on their
properties like their label, Git branch, etc. Other items like
Git commits or issues mentioned in commit messages can also be looked for.

In the top search box, you can:

* select the type of object you look for
* enter search tokens

Upon hitting the _Enter_ key, a search is performed using the token
and the given type if selected.

The search page is displayed and repeats the type and token.

If no result is found, the search page display a warning.

If exactly 1 result is returned, Ontrack will automatically redirect
to the page associated with this result.

If there are more than 1 result, their list is displayed, up to 20 results. If
more results are available, a _More_ link is displayed, which will load up to
20 more results.

[[search-engine]]
==== Searching engine

By default, a built-in engine is used to provide results but this engine is
quite slow and can be replaced by a way-faster ElasticSearch based engine.

NOTE: The ElasticSearch engine will become the default one starting from version 4.0.

See <<integration-elasticsearch>> on how to enable the ElasticSearch based engine.
