[[security]]
=== Security

The Ontrack security is based on accounts and account groups, and on
authorizations granted to them.

[[security-concepts]]
==== Concepts

Each action in Ontrack is associated with an _authorisation function_ and those
functions are grouped together in _roles_ which are granted to _accounts_ and
_account groups_.

An _account_ can belong to several _account groups_ and his set of final
_authorisation functions_ will be the aggregation of the rights given to the
account and to the groups.

[[security-roles]]
==== Roles

NOTE: As of now, only roles can be assigned to groups and accounts, and the
list of roles and their associated functions is defined by Ontrack itself.

Ontrack distinguishes between _global roles_ and _project_ roles.

<<extending,Extensions>> can contribute to built-in roles
and functions - see <<extending-security>> for details.

[[security-roles-global]]
===== Global roles

An **ADMINISTRATOR** has access to all the functions of Ontrack, in all
projects. At least such a role should be defined.

NOTE: By default, right after installation, a default `admin` account is
created with the `ADMINISTRATOR` role, having _admin_ as password. This
password should be changed as soon as possible.

A **CREATOR** can create any project and can, on all projects, configure them,
create branches, manage branch templates, create promotion levels and
validation stamps. This role should be attributed to service users in charge
of automating the definition of projects and branches.

An **AUTOMATION** user can do the same things than a _CREATOR_ but can, on all
projects, additionally edit promotion levels and validation stamps, create
builds, promote and validate them, synchronize branches with their template,
manage account groups and project permissions.
This role is suited for build and integration automation (CI).

A **CONTROLLER** can, on all projects, create builds, promote and validate
them, synchronize branches with their template. It is suited for a basic CI
need when the Ontrack structure already exists and does not need to be created.

A **GLOBAL VALIDATION MANAGER** can manage validation stamps across all projects.

A **READ_ONLY** can view all projects, but cannot perform any action on them.

The global roles can only be assigned by an _administrator_, in the _Account
management_ page, by going to the _Global permissions_ command.

A _global permission_ is created by associating:

* a _permission target_ (an account or a group)
* a _global role_

Creation:

1. type the first letter of the account or the group you want to add a permission for
2. select the account or the group
3. select the role you want to give
4. click on _Submit_

Global permissions are created or deleted, not updated.

[[security-roles-project]]
===== Project roles

A project **OWNER** can perform all operations on a project but to delete it.

A project **PARTICIPANT** has the right to see a project and to add comments
in the validation runs (comment + status change).

A project **VALIDATION_MANAGER** can manage the validation stamps and
create/edit the validation runs.

A project **PROMOTER** can create and delete promotion runs, can change the
validation runs statuses.

A project **PROJECT_MANAGER** cumulates the functions of a PROMOTER and of a
VALIDATION_MANAGER. He can additionally manage branches (creation / edition / deletion) and the common
build filters. He can also assign <<usage-labels,labels>> to the project.

A project **READ_ONLY** user can view this project, but cannot perform any action on it.

Only project owners, automation users and administrators can grant rights
in a project.

In the project page, select the _Permissions_ command.

A _project permission_ is created by associating:

* a _permission target_ (an account or a group)
* a _project role_

Creation:

1. type the first letter of the account or the group you want to add a
   permission for
2. select the account or the group
3. select the role you want to give
4. click on _Submit_

Project permissions are created or deleted, not updated.

[[security-accounts]]
==== Accounts

Accounts are created with either:

* built-in authentication, with a password stored and encrypted in Ontrack
itself
* <<ldap,LDAP setup>>

[[security-accounts-builtin]]
===== Built-in accounts

An _administrator_ can create accounts. He must give them:

* a unique name
* a unique email
* a display name
* an initial password

Any user can change his own password by going to the _Change password_ menu.

The _administrator_ can give an account a list of global or project roles.

[[security-accounts-ldap]]
===== LDAP accounts

Accounts whose authentication is managed by the LDAP are not created directly
but are instead created at first successful login.

As for the other types of accounts, the _administrator_ can give them a list
of global or project roles.

[[security-groups]]
==== Account groups

An _administrator_ can create groups using a name and a description, and assign
them a list of global or project roles.

An account can be assigned to several groups.

NOTE: If LDAP is enabled, some LDAP groups can be <<ldap-mapping,mapped>> to
the account groups.

[[security-general]]
==== General settings

By default, all users (including anonymous ones) have access to all the
projects, at least in read only mode.

You can disable this anonymous access by goint go to the _Settings_ and click
the _Edit_ button in the _General_ section. There you can set the
_Grants project view to all_ option to _No_.

[[security-extending]]
==== Extending the security

<<extending,Extensions>> can extend the security model beyond what
if defined in the Ontrack core. See
<<extending-security>> for more details.
