@startuml
class GlobalRole
class ProjectRole

interface GlobalFunction
interface ProjectFunction

GlobalRole o--> GlobalFunction: "0..*"
GlobalRole o--> ProjectFunction: "0..*"

ProjectRole o--> ProjectFunction: "0..*"
@enduml
