[[testing]]
=== Testing

* _unit tests_ are always run and should not access resources not load the
application context (think: fast!)
* _integration tests_ can access resources or load the application context,
and run against a database
* _acceptance tests_ are run against the deployed and running application.

[[testing-unit]]
==== Running the unit and integration tests

In order to run the _unit tests_ only:

[source,bash]
----
./gradlew test
----

In order to add the _integration tests_:

[source,bash]
----
./gradlew integrationTest
----

From your IDE, you can launch both unit and integration tests using the default
JUnit integration.

[[testing-acceptance]]
==== Acceptance tests

[[testing-acceptance-cmd]]
===== On the command line

NOTE: This requires Docker & Docker Compose to be installed and correctly
configured.

The application can be deployed on a local Docker container, running on SSL with a self signed certificate, and
tested by running all the acceptance tests:

[source,bash]
----
./gradlew ciAcceptanceTest
----

When using a Docker Machine, you will have to specify the Docker host:

[source,bash]
----
./gradlew ciAcceptanceTest -PciMachine=`docker-machine ip build`
----

where `build` is the name of the Docker machine.

If the Docker container used for the tests must be kept, add the `-x ciStop`
to the arguments.

TIP: To only deploy the application in a container without launching any test,
you can also run `./gradlew ciStart`.

[[testing-acceptance-ide]]
===== From the IDE

In order to develop or test acceptance tests, you might want to run them from
your IDE.

1. Make sure you have a running application somewhere, either by launching it
from your IDE (see <<development-ide>>) or by running `ciStart` (see previous
section).

2. Launch all, some or one test in the `ontrack-acceptance` module after having
set the following system properties:

** `ontrack.url` - the URL of the running application to test - defaults to
   http://localhost:8080
** `ontrack.disableSSL` - `true` if the server is running with a self signed
certificate, and if you're using `https`

[[testing-acceptance-sa]]
===== Standalone mode

For testing `ontrack` in real mode, with the application to test deployed on a
remote machine, it is needed to be able to run acceptance tests in standalone
mode, without having to check the code out and to build it.

TIP: Running the acceptance tests using the `ciAcceptanceTest` Gradle task
remains the easiest way.

The acceptance tests are packaged as a standalone JAR, that contains all
the dependencies.

To run the acceptance tests, you need a JDK8 and you have to run the JAR using:


[source,bash]
----
java -jar ontrack-acceptance.jar <options>
----

The options are:

* `--option.acceptance.url=<url>` to specify the `<url>` where `ontrack` is deployed. It
defaults to http://localhost:8080
* `--option.acceptance.admin=<password>` to specify the administrator password. It
defaults to `admin`.
* `--option.acceptance.context=<context>` can be specified several time to define the
context(s) the acceptance tests are running in (like
`--option.acceptance.context=production` for example). According to the context, some
tests can be excluded from the run.

The results of the tests is written as a JUnit XML file, in
`build/acceptance/ontrack-acceptance.xml`.

The directory can be changed using the `ontrack.acceptance.output-dir` argument
or system property and defaults to `build/acceptance`.

The JUnit result file name can be changed using the `ontrack.acceptance.result-file-name` argument
or system property and defaults to `ontrack-acceptance.xml`.

[[testing-dev]]
==== Developing tests

Unit tests are JUnit tests whose class name ends with `Test`.
Integration tests are JUnit tests whose class name ends with `IT`.
Acceptance tests are JUnit tests whose class name starts with `ACC` and are
located in the `ontrack-acceptance` module.

[[testing-dev-unit]]
===== Unit test context

Unit tests do not need any application context or any database.

[[testing-dev-it]]
===== Integration test context

Integration tests will usually load an application context and connect to a
Postgresql database.

For commodity, those tests will inherit from the `AbstractITTestSupport` class,
and more specifically:

* from `AbstractRepositoryTestSupport` for JDBC repository integration tests
* from `AbstractServiceTestSupport` for service integration tests

Configuration for the integration tests is done in the `ITConfig` class.
