[[usage-bitbucket]]
==== Working with BitBucket

https://www.atlassian.com/software/bitbucket[BitBucket] is an enterprise Git
repository manager by Atlassian.

When <<usage-git,working with Git>> in Ontrack, one can configure a project
to connect to a Git repository defined in BitBucket in order to access to the
change logs.

[[usage-bitbucket-config]]
===== General configuration

The access to a BitBucket instance must be configured.

1. as <<security,administrator>>, go to the _BitBucket configurations_ menu
2. click on _Create a configuration_
3. in the configuration dialog, enter the following parameters:
** **Name**  - unique name for the configuration
** **URL** - URL to the Stash instance
** User & Password - credentials used to access Stash - Ontrack only needs a
   read access to the repositories

The existing configurations can be updated and deleted.

[[usage-bitbucket-config]]
===== Project configuration

The link between a project and a Stash repository is defined by the _Stash
configuration_ property:

* **Configuration** - selection of the Stash configuration created before -
  this is used for the access and the issues management
* **Project** - name of the _Stash project_
* **Repository** - name of the _Stash repository_
** Indexation interval - interval (in minutes) between each synchronization
(Ontrack maintains internally a clone of the BitBucket repositories)
** Issue configuration - <<usage-issues,configured issue service>> to use
when looking for issues in commits.

Branches can be <<usage-git,configured for Git>> independently.
