[[usage-gitlab]]
==== Working with GitLab

https://about.gitlab.com[GitLab] unifies issues, code review, CI and CD into
a single UI.

When <<usage-git,working with Git>> in Ontrack, one can configure a project
to connect to a GitLab repository.

[[usage-gitlab-config]]
===== General configuration

The access to a GitLab instance must be configured.

1. as <<security,administrator>>, go to the _GitLab configurations_ menu
2. click on _Create a configuration_
3. in the configuration dialog, enter the following parameters:
** **Name**  - unique name for the configuration
** **URL** - URL to the GitLab instance (not the repository, the GitLab server)
** **User** & **Personal Access Token** - credentials used to access GitLab
** Ignore SSL Certificate - select _Yes_ if the SSL certificate for your GitLab
   instance cannot be trusted by default.

TIP: You cannot use the account's password - only Personal Access Tokens are
supported.s

The existing configurations can be updated and deleted.

[[usage-gitlab-project]]
===== Project configuration

The link between a project and a GitLab repository is defined by the _GitLab
configuration_ property:

* **Configuration** - selection of the GitLab configuration created before -
  this is used for the access
* Issue configuration - select the source of issues for this project. This can
  be any ticketing system (like JIRA) or the built-in issue management for
  this GitLab project (displayed as "GitLab issues")
* **Repository** - repository name, like `nemerosa/ontrack`
* Indexation interval - how often, in minutes, must the content of this
  repository be synchronised with Ontrack. Use `0` to not automatically
  synchronize this repository (this can be done manually).

Branches can be <<usage-git,configured for Git>> independently.
