[[validation-runs]]
=== Managing validation runs

<<model,Validation runs>> associate a validation stamp
to a build, and a status describing the validation: passed,
failed, etc.

Additionally, a <<model,run info>> can be associated with
the validation run to show information like a duration,
a source or a trigger.

Validation runs can be created manually, but more often,
they will be created automatically by a CI engine like
<<integration-jenkins,Jenkins>>.

Validation runs can be seen:

* in the branch overview - only their latest status is
  then visible

* in the branch overview, by clicking on a validation run
  (at the intersection of a validation stamp and a build),
  you can either create a new validation run (when there is
  none) or see the list of them and their statuses.

* in the build page

* in the validation stamp page

For one validation run, one can add comments and update
the status to reflect (for example, to mention that
a failure in under investigation).

[[validation-runs-data]]
==== Validation run data

Some additional data can be associated with a validation run, according
to a format defined by their <<validation-stamps-data,validation stamp>>.
For example, passed and total tests, or a coverage percentage.

When creating a validation run, either though the GUI or through any
of the API, the data will be validated according to the rules defined
by the validation stamp.

In particular, the validation run status (passed, warning, failed, etc.)
will be computed in some cases, when a threshold of quality is associated
with the validation stamp (like a % of passed tests).

In order to use create a validation run with some validation data,
you can also use the <<dsl,DSL>>:

[source,groovy]
----
def build = ...
build.validationWithText("Text data", "PASSED", "Some text")
build.validateWithCHML("CHML data", 1, 10, 100, 1000)
build.validateWithNumber("Number data", 80)
build.validateWithPercentage("Percentage data", 57)
build.validateWithFraction("Fraction data", 99, 100)
----

For a custom validation data type, you can use:

[source,groovy]
----
build.validateWithData(
    "Validation stamp name",
    [:] // Validation data
)
----

NOTE: The actual validation data type is taken from the validation stamp.
