[[usage-subversion]]
==== Working with Subversion

Ontrack allows you to configure projects and branches to work with Subversion
in order to:

* get <<changelogs,change logs>>
* search for issues linked to builds and promotions
* search for revisions

[[usage-subversion-config]]
===== Subversion configurations

In order to be able to associate projects and branches with Subversion
information, an administrator must first define one or several Subversion
configurations.

As an administrator, go to the user menu and select _SVN configurations_.

In this page, you can create, update and delete Subversion configurations.
Parameters for a Subversion configuration are:

* a name - it will be used for the association with projects
* a URL - Ontrack supports `svn`, `http` and `https` protocols - if the SSL
  certificate is not recognized by default, some
  <<appendix-certificates,additional configuration>> must be done at system
  level.

IMPORTANT: The URL must be the URL of the _repository_.

* a user and a password if the access to the repository requires authentication
* a tag filter pattern - optional, a regular expression which defines which
  tags must be indexed
* several URL used for browsing
* indexation interval in minutes (see below)
* indexation start - the revision where to start the indexation from
* issue configuration - issue service associated with this repository

[[usage-subversion-indexation]]
===== Indexation

Ontrack works with Subversion by indexing some repository information locally,
in order to avoid going over the network for each Subversion query.

This indexation is controlled by the parameters of the Subversion
configuration: starting revision and interval. If this interval is set to 0,
the indexation will have to be triggered manually.

Among the information being indexed, the copy of tags is performed and can be
filtered if needed.

In order to access the indexation settings of a Subversion configuration,
click on the _Indexation_ link.

From the indexation dialog, you can:

* force the indexation from the latest indexed revision
* reindex a range of revisions
* erase all indexed information, and rerun it

The indexations run in background.

[[usage-subversion-project]]
===== Project configuration

You can associate a project with a Subversion configuration by adding the
_SVN configuration_ property and selecting:

* a Subversion configuration using its name
* a reference path (typically to the `trunk`)

IMPORTANT: Like all paths in Subversion configurations of projects and
           branches, this is a _relative_ path to the root of the repository.
           _Not_ an absolute URL.

From then on, you can start configuring the branches of the project.

[[usage-subversion-branch]]
===== Branch configuration

You can associate a branch with Subversion by adding the _SVN configuration_
property and selecting:

* a path to the branch
* a build revision link and its configuration if any

IMPORTANT: The path to the branch is _relative_ to the URL of the SVN
           repository.

The build commit link defines how to associate a <<model,build>> and a
location in Subversion (tag, revision, ...). This link works in both directions
since we need also to find builds based on Subversion informations.

Build commit links are extension points - the following are available in
Ontrack.

[[usage-subversion-link-tag]]
====== Tag name

The build name is considered a tag name in the `tags` folder for the branch.
For example, if the branch path is `/projects/myproject/branches/1.1` then the
tags folder is `/projects/myproject/tags` and build names will be looked for
in this folder.

No configuration is needed.

[[usage-subversion-link-tag-pattern]]
====== Tag pattern name

The build name is considered a tag name in the `tags` folder but must follow
a given pattern.

[[usage-subversion-link-revision]]
====== Revision name

The build name is always numeric and represent a revision on the branch path.

No configuration is needed.

[[usage-subversion-link-revision-pattern]]
====== Revision pattern

The build name has the branch revision in its name, using the `{revision}`
token, following a given pattern. For example, if the pattern is
`2.0.*-{revision}`, then all build names must start with `2.0.`, following
by anything and suffixed by a revision number.
