rootProject.name = "ontrack"

include(":ontrack-common")
include(":ontrack-json")
include(":ontrack-test-utils")
// TODO include(":ontrack-model")
// TODO include(":ontrack-client")
// TODO include(":ontrack-job")
// TODO include(":ontrack-git")
// TODO include(":ontrack-extension-api")
// TODO include(":ontrack-extension-support")
// TODO include(":ontrack-it-utils")
// TODO include(":ontrack-database")
// TODO include(":ontrack-rabbitmq")
// TODO include(":ontrack-repository")
// TODO include(":ontrack-repository-impl")
// TODO include(":ontrack-repository-support")
// TODO include(":ontrack-service")
// TODO include(":ontrack-tx")
// TODO include(":ontrack-ui")
// TODO include(":ontrack-ui-graphql")
// TODO include(":ontrack-ui-support")
// TODO include(":ontrack-web")
// TODO include(":ontrack-web-core")
// TODO include(":ontrack-web-tests")
// TODO include(":ontrack-docs")

// KDSL
// TODO include(":ontrack-kdsl")
// TODO include(":ontrack-kdsl-acceptance")

// Core extensions
// TODO include(":ontrack-extension-ldap")
// TODO include(":ontrack-extension-oidc")
// TODO include(":ontrack-extension-artifactory")
// TODO include(":ontrack-extension-general")
// TODO include(":ontrack-extension-issues")
// TODO include(":ontrack-extension-combined")
// TODO include(":ontrack-extension-jenkins")
// TODO include(":ontrack-extension-jira")
// TODO include(":ontrack-extension-scm")
// TODO include(":ontrack-extension-git")
// TODO include(":ontrack-extension-github")
// TODO include(":ontrack-extension-gitlab")
// TODO include(":ontrack-extension-stash")
// TODO include(":ontrack-extension-bitbucket-cloud")
// TODO include(":ontrack-extension-stale")
// TODO include(":ontrack-extension-vault")
// TODO include(":ontrack-extension-influxdb")
// TODO include(":ontrack-extension-sonarqube")
// TODO include(":ontrack-extension-indicators")
// TODO include(":ontrack-extension-casc")
// TODO include(":ontrack-extension-elastic")
// TODO include(":ontrack-extension-notifications")
// TODO include(":ontrack-extension-slack")
// TODO include(":ontrack-extension-chart")
// TODO include(":ontrack-extension-delivery-metrics")
// TODO include(":ontrack-extension-auto-versioning")
// TODO include(":ontrack-extension-license")
// TODO include(":ontrack-extension-tfc")
// TODO include(":ontrack-extension-recordings")
// TODO include(":ontrack-extension-hook")
// TODO include(":ontrack-extension-queue")
// TODO include(":ontrack-extension-workflows")
// TODO include(":ontrack-extension-environments")
