# Base
FROM java:openjdk-8u45-jdk

# Meta-information
MAINTAINER Damien Coraboeuf <damien.coraboeuf@gmail.com>

# JDK installation
RUN apt-get update && apt-get install -y openjdk-8-jdk

# Exposing the ports
EXPOSE 443
