@startuml

[new]
[PASSED]
[WARNING]
[DEFECTIVE]
[EXPLAINED]
[FAILED]
[FIXED]
[INTERRUPTED]
[INVESTIGATING]

[new] --> [PASSED]
[new] --> [FAILED]
[new] --> [WARNING]

[EXPLAINED] --> [FIXED]

[INVESTIGATING] --> [DEFECTIVE]
[INVESTIGATING] --> [EXPLAINED]
[INVESTIGATING] --> [FIXED]

[INTERRUPTED] --> [INVESTIGATING]
[INTERRUPTED] --> [FIXED]

[FAILED] --> [INTERRUPTED]
[FAILED] --> [INVESTIGATING]
[FAILED] --> [EXPLAINED]
[FAILED] --> [DEFECTIVE]

[WARNING] --> [INTERRUPTED]
[WARNING] --> [INVESTIGATING]
[WARNING] --> [EXPLAINED]
[WARNING] --> [DEFECTIVE]

@enduml