-- v0
-- Initial schema

CREATE TABLE ONTRACK_VERSION (
  VALUE   INTEGER   NOT NULL,
  UPDATED TIMESTAMP NOT NULL
);

CREATE TABLE PROJECTS (
  ID          INTEGER      NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(40)  NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  CONSTRAINT PROJECTS_PK PRIMARY KEY (ID),
  CONSTRAINT PROJECTS_UQ UNIQUE (NAME)
);

