-- Application log entries (#467)

CREATE TABLE APPLICATION_LOG_ENTRIES (
  ID             SERIAL       NOT NULL,
  LEVEL          VARCHAR(10)  NOT NULL,
  TIMESTAMP      VARCHAR(24)  NOT NULL,
  AUTHENTICATION VARCHAR(40),
  NAME           VARCHAR(200) NOT NULL,
  DESCRIPTION    VARCHAR(500),
  INFORMATION    TEXT,
  EXCEPTION      TEXT,
  DETAILS        TEXT,
  CONSTRAINT APPLICATION_LOG_ENTRIES_PK PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS APPLICATION_LOG_ENTRIES_IX_LEVEL
  ON APPLICATION_LOG_ENTRIES (LEVEL);

CREATE INDEX IF NOT EXISTS APPLICATION_LOG_ENTRIES_IX_AUTHENTICATION
  ON APPLICATION_LOG_ENTRIES (AUTHENTICATION);
