[[notification-backend-jenkins]]
==== Jenkins (`jenkins`)

This channel is used to trigger remote Jenkins jobs with some parameters.



_This channel does not use the custom template._

Links:

* <<integration-jenkins-notifications,Jenkins notifications>>

Configuration:

* **callMode** - ASYNC, SYNC - required - How to call the Jenkins job. ASYNC (the default) means that the job is called in "fire and forget" mode. When set to SYNC, Ontrack will wait for the completion of the job to success, with a given timeout (not recommended).

* **config** - String - required - Name of the Jenkins configuration to use for the connection.

* **job** - String - required - URL of the Jenkins job to call

* **parameters** - List - required - Parameters to send to to the job

** **name** - String - required - Name of the parameter

** **value** - String - required - Value of the parameter

* **timeout** - Int - required - Timeout in seconds

Output:

* **buildUrl** - String - optional - URL to the build (only available when call mode is SYNC)

* **jobUrl** - String - required - URL to the job

* **parameters** - List - required - Parameters sent to the job

** **name** - String - required - Name of the parameter

** **value** - String - required - Value of the parameter

