When working with <<usage-git,Git>>, the access to the Git repositories must be configured.

`def git(Map<String, ?> parameters, String name)`

The `name` is the identifier of the configuration - if it already exists, it will be updated.

The parameters are the following:

!===
! Parameter ! Description

! **remote** ! the remote location
! user ! user used to connect to GitHub (optional)
! password ! password used to connect to GitHub (optional)
! commitLink ! Link to a commit, using `{commit}` as placeholder
! fileAtCommitLink ! Link to a file at a given commit, using `{commit}` and `{path}` as placeholders
! indexationInterval ! interval (in minutes) between each synchronisation (Ontrack maintains internally a clone of
  the GitHub repository)
! issueServiceConfigurationIdentifier ! identifier for the linked issues (see example <<usage-jira,here>>)

!===

See the <<usage-git,documentation>> to know the meaning of those parameters.

Example:

[source,groovy]
----
ontrack.configure {
   git 'ontrack', remote: 'https://github.com/nemerosa/ontrack.git', user: 'test', password: 'secret'
}
assert ontrack.config.git.find { it == 'ontrack' } != null
----
