[[templating-source-changelog]]
===== changelog

Renders a change log for this promotion run.

The "to build" is the one being promoted.
 
The "from build" is the last build (before this one) having been promoted to the associated
promotion level.

If no such previous build is found on the associated branch, the search will be done
across the whole project, unless the `acrossBranches` configuration parameter is set to `false`.

If `project` is set to a comma-separated list of strings, the change log will be rendered 
for the recursive links, in the order to the projects being set (going deeper and deeper
in the links). 

Applicable for:

* promotion run

Configuration:

* **acrossBranches** - Boolean - required - By default, if a previous promotion is not found on the current branch, it'll be looked for in all branches of the projects. Set this parameter to `false` to disable this behaviour.

* **allQualifiers** - Boolean - required - Loop over all qualifiers for the last level of `dependencies`, including the default one. Qualifiers at `dependencies` take precedence.

* **commitsOption** - NONE, OPTIONAL, ALWAYS - required - Defines how to render commits for a change log

* **defaultQualifierFallback** - Boolean - required - If a qualifier has no previous link, uses the default qualifier (empty) qualifier.

* **dependencies** - List - required - Comma-separated list of project links to follow one by one for a get deep change log. Each item in the list is either a project name, or a project name and qualifier separated by a colon (:).

* **empty** - String - required - String to use to render an empty or non existent change log

* **title** - Boolean - required - Include a title for the change log

Example:

[source]
----
${promotionRun.changelog}
----
