-- Validation data (#176)

ALTER TABLE VALIDATION_STAMPS
  ADD DATA_TYPE_ID VARCHAR(120) NULL;

ALTER TABLE VALIDATION_STAMPS
  ADD DATA_TYPE_CONFIG VARCHAR(10000) NULL;

CREATE TABLE VALIDATION_RUN_DATA (
  VALIDATION_RUN INTEGER NOT NULL,
  DATA_TYPE_ID VARCHAR(120) NOT NULL,
  DATA VARCHAR(10000) NULL,
  CONSTRAINT VALIDATION_RUN_DATA_PK PRIMARY KEY (VALIDATION_RUN),
  CONSTRAINT VALIDATION_RUN_DATA_FK_VALIDATION_RUN FOREIGN KEY (VALIDATION_RUN) REFERENCES VALIDATION_RUNS (ID) ON DELETE CASCADE
);
