-- Validation data as JSONB (#176)

ALTER TABLE VALIDATION_RUN_DATA
  ALTER COLUMN DATA TYPE JSONB USING DATA::JSONB;

ALTER TABLE VALIDATION_STAMPS
  ALTER COLUMN DATA_TYPE_CONFIG TYPE JSONB USING DATA_TYPE_CONFIG::JSONB;

