-- Labels (#615)

CREATE TABLE LABEL (
  ID          SERIAL        NOT NULL,
  CATEGORY    VARCHAR(50)  NULL,
  NAME        VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(500) NULL,
  COLOR       VARCHAR(20)  NOT NULL,
  COMPUTED_BY VARCHAR(200) NULL,
  CONSTRAINT LABEL_PK PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS LABEL_IX_CATEGORY_NAME
  ON LABEL (CATEGORY, NAME);

CREATE TABLE PROJECT_LABEL (
  ID          SERIAL       NOT NULL,
  PROJECT_ID  INTEGER      NOT NULL,
  LABEL_ID    INTEGER      NOT NULL,
  CONSTRAINT PROJECT_LABEL_FK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE,
  CONSTRAINT PROJECT_LABEL_FK_LABEL FOREIGN KEY (LABEL_ID) REFERENCES LABEL (ID) ON DELETE CASCADE
);
