-- 20. Branch favourites (#632)

CREATE TABLE BRANCH_FAVOURITES (
  ID        SERIAL  NOT NULL,
  ACCOUNTID INTEGER NOT NULL,
  BRANCHID INTEGER NOT NULL,
  CONSTRAINT BRANCH_FAVOURITES_PK PRIMARY KEY (ID),
  CONSTRAINT BRANCH_FAVOURITES_UQ UNIQUE (ACCOUNTID, BRANCHID),
  CONSTRAINT BRANCH_FAVOURITES_FK_ACCOUNT FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE,
  CONSTRAINT BRANCH_FAVOURITES_FK_BRANCH FOREIGN KEY (BRANCHID) REFERENCES BRANCHES (ID) ON DELETE CASCADE
);
