-- 25. Missing indexes

CREATE INDEX IF NOT EXISTS BRANCH_FAVOURITES_IX_ACCOUNT ON BRANCH_FAVOURITES (ACCOUNTID);
CREATE INDEX IF NOT EXISTS BRANCH_FAVOURITES_IX_BRANCH ON BRANCH_FAVOURITES (BRANCHID);
CREATE INDEX IF NOT EXISTS BRANCH_FAVOURITES_IX_ACCOUNT_BRANCH ON BRANCH_FAVOURITES (ACCOUNTID, BRANCHID);

CREATE INDEX IF NOT EXISTS PROJECT_FAVOURITES_IX_ACCOUNT ON PROJECT_FAVOURITES (ACCOUNTID);
CREATE INDEX IF NOT EXISTS PROJECT_FAVOURITES_IX_BRANCH ON PROJECT_FAVOURITES (PROJECTID);
CREATE INDEX IF NOT EXISTS PROJECT_FAVOURITES_IX_ACCOUNT_PROJECT ON PROJECT_FAVOURITES (ACCOUNTID, PROJECTID);
