-- 26. Removing support for Subversion

DROP TABLE IF EXISTS EXT_SVN_REVISION_ISSUE;
DROP TABLE IF EXISTS EXT_SVN_STOP;
DROP TABLE IF EXISTS EXT_SVN_COPY;
DROP TABLE IF EXISTS EXT_SVN_MERGE_REVISION;
DROP TABLE IF EXISTS EXT_SVN_REVISION;
DROP TABLE IF EXISTS EXT_SVN_REPOSITORY;
