-- 27. Removing support for branch templates

DROP TABLE IF EXISTS BRANCH_TEMPLATE_INSTANCE_PARAMS;
DROP TABLE IF EXISTS BRANCH_TEMPLATE_INSTANCES;
DROP TABLE IF EXISTS BRANCH_TEMPLATE_DEFINITION_PARAMS;
DROP TABLE IF EXISTS BRANCH_TEMPLATE_DEFINITIONS;
