-- 28. Security updates

ALTER TABLE ACCOUNT_GROUPS
    ADD AUTOJOIN BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE PROVIDED_GROUPS
(
    ACCOUNT    INTEGER     NOT NULL,
    MODE       VARCHAR(20) NOT NULL,
    GROUP_NAME VARCHAR(80) NOT NULL,
    CONSTRAINT PROVIDED_GROUPS_PK PRIMARY KEY (ACCOUNT, MODE, GROUP_NAME),
    CONSTRAINT PROVIDED_GROUPS_FK_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE
);

CREATE INDEX PROVIDED_GROUPS_IX_ACCOUNT ON PROVIDED_GROUPS (ACCOUNT);
CREATE INDEX PROVIDED_GROUPS_IX_ACCOUNT_MODE ON PROVIDED_GROUPS (ACCOUNT, MODE);

CREATE TABLE TOKENS
(
    ID          SERIAL PRIMARY KEY NOT NULL,
    ACCOUNT     INTEGER            NOT NULL,
    VALUE       VARCHAR(256)       NOT NULL,
    CREATION    VARCHAR(24)        NOT NULL,
    VALID_UNTIL VARCHAR(24)        NULL,
    CONSTRAINT TOKENS_FK_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX TOKENS_UQ_ACCOUNT ON TOKENS (ACCOUNT);
CREATE UNIQUE INDEX IF NOT EXISTS TOKENS_IX_VALUE ON TOKENS (VALUE);
