-- 28. Security updates

-- Using provider+source instead of mode for accounts

ALTER TABLE ACCOUNTS
    ADD PROVIDER VARCHAR(20) NULL;

ALTER TABLE ACCOUNTS
    ADD SOURCE VARCHAR(20) NULL;

UPDATE ACCOUNTS
SET PROVIDER = 'built-in',
    SOURCE   = ''
WHERE MODE = 'password';

UPDATE ACCOUNTS
SET PROVIDER = 'ldap',
    SOURCE   = ''
WHERE MODE = 'ldap';

ALTER TABLE ACCOUNTS
    DROP COLUMN MODE;

ALTER TABLE ACCOUNTS
    ALTER COLUMN PROVIDER SET NOT NULL;

ALTER TABLE ACCOUNTS
    ALTER COLUMN SOURCE SET NOT NULL;

-- Using provider+source instead of mode for account group mappings

ALTER TABLE ACCOUNT_GROUP_MAPPING
    RENAME COLUMN SOURCE TO ORIGIN;

ALTER TABLE ACCOUNT_GROUP_MAPPING
    ADD PROVIDER VARCHAR(20) NULL;

ALTER TABLE ACCOUNT_GROUP_MAPPING
    ADD SOURCE VARCHAR(20) NULL;

UPDATE ACCOUNT_GROUP_MAPPING
SET PROVIDER = 'ldap',
    SOURCE   = ''
WHERE MAPPING = 'ldap';

ALTER TABLE ACCOUNT_GROUP_MAPPING
    DROP COLUMN MAPPING;

ALTER TABLE ACCOUNT_GROUP_MAPPING
    ALTER COLUMN PROVIDER SET NOT NULL;

ALTER TABLE ACCOUNT_GROUP_MAPPING
    ALTER COLUMN SOURCE SET NOT NULL;

-- Other upgrades

CREATE TABLE PROVIDED_GROUPS
(
    ACCOUNT    INTEGER     NOT NULL,
    PROVIDER   VARCHAR(20) NOT NULL,
    SOURCE     VARCHAR(20) NOT NULL,
    GROUP_NAME VARCHAR(80) NOT NULL,
    CONSTRAINT PROVIDED_GROUPS_PK PRIMARY KEY (ACCOUNT, PROVIDER, SOURCE, GROUP_NAME),
    CONSTRAINT PROVIDED_GROUPS_FK_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE
);

CREATE INDEX PROVIDED_GROUPS_IX_ACCOUNT ON PROVIDED_GROUPS (ACCOUNT);
CREATE INDEX PROVIDED_GROUPS_IX_ACCOUNT_MODE ON PROVIDED_GROUPS (ACCOUNT, PROVIDER, SOURCE);

CREATE TABLE TOKENS
(
    ID          SERIAL PRIMARY KEY NOT NULL,
    ACCOUNT     INTEGER            NOT NULL,
    VALUE       VARCHAR(256)       NOT NULL,
    CREATION    VARCHAR(24)        NOT NULL,
    VALID_UNTIL VARCHAR(24)        NULL,
    CONSTRAINT TOKENS_FK_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX TOKENS_UQ_ACCOUNT ON TOKENS (ACCOUNT);
CREATE UNIQUE INDEX IF NOT EXISTS TOKENS_IX_VALUE ON TOKENS (VALUE);
