-- 30. Default document service storage

CREATE TABLE DOCUMENTS
(
    STORE    VARCHAR(80)  NOT NULL,
    NAME     VARCHAR(500) NOT NULL,
    DOCTYPE  VARCHAR(40)  NOT NULL,
    DOCBYTES BYTEA        NOT NULL,
    CONSTRAINT DOCUMENTS_PK PRIMARY KEY (STORE, NAME)
);

CREATE INDEX DOCUMENTS_IX_STORE ON DOCUMENTS (STORE);
