-- 33. Increasing the max length for a validation stamp name

ALTER TABLE VALIDATION_STAMPS ALTER COLUMN NAME TYPE VARCHAR(120);
ALTER TABLE PREDEFINED_VALIDATION_STAMPS ALTER COLUMN NAME TYPE VARCHAR(120);
