-- 35. Additional entities for events

ALTER TABLE EVENTS
    ADD X_PROJECT INTEGER
        DEFAULT NULL
        REFERENCES PROJECTS ON DELETE CASCADE;

ALTER TABLE EVENTS
    ADD X_BRANCH INTEGER
        DEFAULT NULL
        REFERENCES BRANCHES ON DELETE CASCADE;

ALTER TABLE EVENTS
    ADD X_BUILD INTEGER
        DEFAULT NULL
        REFERENCES BUILDS ON DELETE CASCADE;

ALTER TABLE EVENTS
    ADD X_PROMOTION_LEVEL INTEGER
        DEFAULT NULL
        REFERENCES PROMOTION_LEVELS ON DELETE CASCADE;

ALTER TABLE EVENTS
    ADD X_PROMOTION_RUN INTEGER
        DEFAULT NULL
        REFERENCES PROMOTION_RUNS ON DELETE CASCADE;

ALTER TABLE EVENTS
    ADD X_VALIDATION_STAMP INTEGER
        DEFAULT NULL
        REFERENCES VALIDATION_STAMPS ON DELETE CASCADE;

ALTER TABLE EVENTS
    ADD X_VALIDATION_RUN INTEGER
        DEFAULT NULL
        REFERENCES VALIDATION_RUNS ON DELETE CASCADE;

CREATE INDEX EVENTS_FK_X_PROJECT ON EVENTS (X_PROJECT);
CREATE INDEX EVENTS_FK_X_BRANCH ON EVENTS (X_BRANCH);
CREATE INDEX EVENTS_FK_X_BUILD ON EVENTS (X_BUILD);
CREATE INDEX EVENTS_FK_X_PROMOTION_LEVEL ON EVENTS (X_PROMOTION_LEVEL);
CREATE INDEX EVENTS_FK_X_PROMOTION_RUN ON EVENTS (X_PROMOTION_RUN);
CREATE INDEX EVENTS_FK_X_VALIDATION_STAMP ON EVENTS (X_VALIDATION_STAMP);
CREATE INDEX EVENTS_FK_X_VALIDATION_RUN ON EVENTS (X_VALIDATION_RUN);
