-- 35. Additional entities for events

ALTER TABLE EVENTS
    ADD X_PROJECT INTEGER
        DEFAULT NULL
        REFERENCES PROJECTS ON DELETE CASCADE;

CREATE INDEX EVENTS_FK_X_PROJECT ON EVENTS (X_PROJECT);
