-- Indexes on the entity_data table (#1057)

CREATE INDEX IF NOT EXISTS ENTITY_DATA_IX_NAME
    ON ENTITY_DATA (NAME);

CREATE INDEX IF NOT EXISTS ENTITY_DATA_IX_NAME_PROJECT
    ON ENTITY_DATA (NAME, PROJECT);

CREATE INDEX IF NOT EXISTS ENTITY_DATA_IX_NAME_BRANCH
    ON ENTITY_DATA (NAME, BRANCH);

CREATE INDEX IF NOT EXISTS ENTITY_DATA_IX_NAME_BUILD
    ON ENTITY_DATA (NAME, BUILD);

CREATE INDEX IF NOT EXISTS ENTITY_DATA_IX_NAME_PROMOTION_LEVEL
    ON ENTITY_DATA (NAME, PROMOTION_LEVEL);

CREATE INDEX IF NOT EXISTS ENTITY_DATA_IX_NAME_PROMOTION_RUN
    ON ENTITY_DATA (NAME, PROMOTION_RUN);

CREATE INDEX IF NOT EXISTS ENTITY_DATA_IX_NAME_VALIDATION_STAMP
    ON ENTITY_DATA (NAME, VALIDATION_STAMP);

CREATE INDEX IF NOT EXISTS ENTITY_DATA_IX_NAME_VALIDATION_RUN
    ON ENTITY_DATA (NAME, VALIDATION_RUN);
