-- 39. Multiple scoped tokens per account

ALTER TABLE TOKENS ADD COLUMN NAME VARCHAR(64) NOT NULL DEFAULT 'default';
ALTER TABLE TOKENS ADD COLUMN SCOPE VARCHAR(32) NOT NULL DEFAULT 'USER';

DROP INDEX IF EXISTS TOKENS_UQ_ACCOUNT;

CREATE UNIQUE INDEX TOKENS_UQ_ACCOUNT ON TOKENS (ACCOUNT, NAME);
