-- 43. Missing indexes

CREATE INDEX IF NOT EXISTS BRANCHES_IX_PROJECT ON BRANCHES (PROJECTID);

CREATE INDEX IF NOT EXISTS BUILDS_IX_BRANCH ON BUILDS (BRANCHID);

CREATE INDEX IF NOT EXISTS PROMOTION_LEVELS_IX_BRANCH ON PROMOTION_LEVELS (BRANCHID);

CREATE INDEX IF NOT EXISTS VALIDATION_STAMPS_IX_BRANCH ON VALIDATION_STAMPS (BRANCHID);

CREATE INDEX IF NOT EXISTS VALIDATION_RUNS_IX_BUILD ON VALIDATION_RUNS (BUILDID);
CREATE INDEX IF NOT EXISTS VALIDATION_RUNS_IX_VALIDATION_STAMP ON VALIDATION_RUNS (VALIDATIONSTAMPID);
CREATE INDEX IF NOT EXISTS VALIDATION_RUNS_IX_BUILD_VALIDATION_STAMP ON VALIDATION_RUNS (BUILDID, VALIDATIONSTAMPID);

CREATE INDEX IF NOT EXISTS PROMOTION_RUNS_IX_BUILD ON PROMOTION_RUNS (BUILDID);
CREATE INDEX IF NOT EXISTS PROMOTION_RUNS_IX_VALIDATION_STAMP ON PROMOTION_RUNS (PROMOTIONLEVELID);
CREATE INDEX IF NOT EXISTS PROMOTION_RUNS_IX_BUILD_VALIDATION_STAMP ON PROMOTION_RUNS (BUILDID, PROMOTIONLEVELID);

CREATE INDEX IF NOT EXISTS PROPERTIES_IX_TYPE_PROJECT ON PROPERTIES (TYPE, PROJECT);
CREATE INDEX IF NOT EXISTS PROPERTIES_IX_TYPE_BRANCH ON PROPERTIES (TYPE, BRANCH);
CREATE INDEX IF NOT EXISTS PROPERTIES_IX_TYPE_PROMOTION_LEVEL ON PROPERTIES (TYPE, PROMOTION_LEVEL);
CREATE INDEX IF NOT EXISTS PROPERTIES_IX_TYPE_VALIDATION_STAMP ON PROPERTIES (TYPE, VALIDATION_STAMP);
CREATE INDEX IF NOT EXISTS PROPERTIES_IX_TYPE_BUILD ON PROPERTIES (TYPE, BUILD);
CREATE INDEX IF NOT EXISTS PROPERTIES_IX_TYPE_PROMOTION_RUN ON PROPERTIES (TYPE, PROMOTION_RUN);
CREATE INDEX IF NOT EXISTS PROPERTIES_IX_TYPE_VALIDATION_RUN ON PROPERTIES (TYPE, VALIDATION_RUN);
