-- 46. Slot workflows

CREATE TABLE ENV_SLOT_WORKFLOWS
(
    ID       VARCHAR(36) NOT NULL PRIMARY KEY,
    SLOT_ID  VARCHAR(36) NOT NULL,
    TRIGGER  VARCHAR(24) NOT NULL,
    WORKFLOW JSONB       NOT NULL,
    CONSTRAINT ENV_SLOT_WORKFLOWS_FK_ENV_SLOT FOREIGN KEY (SLOT_ID) REFERENCES ENV_SLOTS (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ENV_SLOT_WORKFLOWS_IX_SLOT ON ENV_SLOT_WORKFLOWS (SLOT_ID);
CREATE INDEX IF NOT EXISTS ENV_SLOT_WORKFLOWS_IX_SLOT_TRIGGER ON ENV_SLOT_WORKFLOWS (SLOT_ID, TRIGGER);

CREATE TABLE ENV_SLOT_WORKFLOW_INSTANCES
(
    ID                   VARCHAR(36) NOT NULL PRIMARY KEY,
    PIPELINE_ID          VARCHAR(36) NOT NULL,
    SLOT_WORKFLOW_ID     VARCHAR(36) NOT NULL,
    START                VARCHAR(24) NOT NULL,
    WORKFLOW_INSTANCE_ID VARCHAR(64) NOT NULL,
    CONSTRAINT ENV_SLOT_WORKFLOW_INSTANCES_FK_ENV_SLOT_PIPELINE FOREIGN KEY (PIPELINE_ID) REFERENCES ENV_SLOT_PIPELINE (ID) ON DELETE CASCADE,
    CONSTRAINT ENV_SLOT_WORKFLOW_INSTANCES_FK_ENV_SLOT_WORKFLOW FOREIGN KEY (SLOT_WORKFLOW_ID) REFERENCES ENV_SLOT_WORKFLOWS (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ENV_SLOT_WORKFLOW_INSTANCES_IX_PIPELINE ON ENV_SLOT_WORKFLOW_INSTANCES (PIPELINE_ID);
CREATE INDEX IF NOT EXISTS ENV_SLOT_WORKFLOW_INSTANCES_IX_SLOT_WORKFLOW ON ENV_SLOT_WORKFLOW_INSTANCES (SLOT_WORKFLOW_ID);
CREATE INDEX IF NOT EXISTS ENV_SLOT_WORKFLOW_INSTANCES_IX_SLOT_WORKFLOW_PIPELINE ON ENV_SLOT_WORKFLOW_INSTANCES (PIPELINE_ID, SLOT_WORKFLOW_ID);
