-- 47. Workflow store

CREATE TABLE WKF_INSTANCES
(
    ID        VARCHAR(128) NOT NULL PRIMARY KEY,
    TIMESTAMP VARCHAR(24)  NOT NULL,
    WORKFLOW  JSONB        NOT NULL,
    EVENT     JSONB        NOT NULL
);


CREATE TABLE WKF_INSTANCES_NODES
(
    WKF_INSTANCES_ID VARCHAR(128) NOT NULL,
    NODE_ID          VARCHAR(128) NOT NULL,
    STATUS           VARCHAR(36)  NOT NULL,
    START_TIME       VARCHAR(24)  NULL,
    END_TIME         VARCHAR(24)  NULL,
    OUTPUT           JSONB        NULL,
    ERROR            VARCHAR(500) NULL,
    PRIMARY KEY (WKF_INSTANCES_ID, NODE_ID),
    CONSTRAINT WKF_INSTANCES_NODES_FK_WKF_INSTANCES FOREIGN KEY (WKF_INSTANCES_ID) REFERENCES WKF_INSTANCES (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS WKF_INSTANCES_NODES_IX_WKF_INSTANCES ON WKF_INSTANCES_NODES (WKF_INSTANCES_ID);
