-- 47. Parallel workflows

CREATE TABLE WKF_INSTANCES
(
    ID        VARCHAR(128) NOT NULL PRIMARY KEY,
    TIMESTAMP VARCHAR(24)  NOT NULL,
    WORKFLOW  JSONB        NOT NULL,
    EVENT     JSONB        NOT NULL
);

CREATE TABLE WKF_INSTANCE_NODES
(
    INSTANCE_ID VARCHAR(128) NOT NULL,
    NODE_ID     VARCHAR(128) NOT NULL,
    STATUS      VARCHAR(32)  NOT NULL,
    START_TIME  VARCHAR(24)  NULL,
    END_TIME    VARCHAR(24)  NULL,
    OUTPUT      JSONB        NULL,
    ERROR       TEXT         NULL,
    CONSTRAINT WKF_INSTANCE_NODES_PK PRIMARY KEY (INSTANCE_ID, NODE_ID),
    CONSTRAINT WKF_INSTANCE_NODES_FK_INSTANCE FOREIGN KEY (INSTANCE_ID) REFERENCES WKF_INSTANCES (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS WKF_INSTANCE_NODES_IX_INSTANCE ON WKF_INSTANCE_NODES (INSTANCE_ID);
