-- 50. Slot workflows can be overridden

ALTER TABLE ENV_SLOT_WORKFLOW_INSTANCES
    ADD COLUMN "USER"           VARCHAR(40)  NULL,
    ADD COLUMN TIMESTAMP        VARCHAR(24)  NULL,
    ADD COLUMN OVERRIDE         BOOLEAN      NULL,
    ADD COLUMN OVERRIDE_MESSAGE VARCHAR(500) NULL;

ALTER TABLE ENV_SLOT_PIPELINE_ADMISSION_RULE_STATUS
    DROP COLUMN "USER",
    DROP COLUMN TIMESTAMP,
    DROP COLUMN OVERRIDE,
    ADD COLUMN DATA_USER          VARCHAR(40) NULL,
    ADD COLUMN DATA_TIMESTAMP     VARCHAR(24) NULL,
    ADD COLUMN OVERRIDE_USER      VARCHAR(40) NULL,
    ADD COLUMN OVERRIDE_TIMESTAMP VARCHAR(24) NULL;

ALTER TABLE ENV_SLOT_PIPELINE_CHANGE
    DROP COLUMN OVERRIDE,
    ADD COLUMN DATA_CHANGED BOOLEAN DEFAULT FALSE,
    ADD COLUMN OVERRIDDEN   BOOLEAN DEFAULT FALSE;
