-- 55. Context data for a workflow instance

CREATE TABLE WKF_INSTANCE_CONTEXT
(
    INSTANCE_ID VARCHAR(128) NOT NULL,
    CONTEXT_ID  VARCHAR(128) NOT NULL,
    HANDLER_ID  VARCHAR(128) NOT NULL,
    DATA        JSONB        NOT NULL,
    CONSTRAINT WKF_INSTANCE_CONTEXT_PK PRIMARY KEY (INSTANCE_ID, CONTEXT_ID),
    CONSTRAINT WKF_INSTANCE_CONTEXT_FK_INSTANCE FOREIGN KEY (INSTANCE_ID) REFERENCES WKF_INSTANCES (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS WKF_INSTANCE_CONTEXT_IX_INSTANCE ON WKF_INSTANCE_NODES (INSTANCE_ID);
