-- 58. Cleanup of accounts

DROP TABLE ACCOUNT_GROUP_MAPPING;
DROP TABLE PROVIDED_GROUPS;

ALTER TABLE ACCOUNTS
    DROP COLUMN PASSWORD;

ALTER TABLE ACCOUNTS
    DROP COLUMN ROLE;

ALTER TABLE ACCOUNTS
    DROP COLUMN PROVIDER;

ALTER TABLE ACCOUNTS
    DROP COLUMN SOURCE;

ALTER TABLE ACCOUNTS
    DROP COLUMN DISABLED;

ALTER TABLE ACCOUNTS
    DROP COLUMN LOCKED;
