-- 61. IdP groups for an account

CREATE TABLE ACCOUNT_IDP_GROUPS
(
    ID         SERIAL PRIMARY KEY NOT NULL,
    ACCOUNT_ID INTEGER            NOT NULL,
    NAME       VARCHAR(64)        NOT NULL,
    CONSTRAINT ACCOUNT__IDP_GROUPS_FK_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ACCOUNT_IDP_GROUPS_UQ_NAME ON ACCOUNT_IDP_GROUPS (ACCOUNT_ID, NAME);
