-- 61. IdP groups for an account

CREATE TABLE GROUP_MAPPINGS
(
    ID        SERIAL PRIMARY KEY NOT NULL,
    IDP_GROUP VARCHAR(128)       NOT NULL,
    GROUP_ID  INTEGER            NOT NULL,
    CONSTRAINT GROUP_MAPPINGS_FK_ACCOUNT_GROUP FOREIGN KEY (GROUP_ID) REFERENCES ACCOUNT_GROUPS (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX GROUP_MAPPINGS_UQ ON GROUP_MAPPINGS (IDP_GROUP, GROUP_ID);
