-- 63. Keeping only the email of existing accounts

DROP INDEX ACCOUNTS_UQ_NAME;

DELETE FROM ACCOUNTS A1
    USING ACCOUNTS A2
WHERE A1.EMAIL = A2.EMAIL
  AND A1.ID < A2.ID;

CREATE UNIQUE INDEX ACCOUNTS_UQ_EMAIL ON ACCOUNTS (EMAIL);

ALTER TABLE ACCOUNTS
    DROP COLUMN NAME;
