-- 66. Specific table for the indexation of build commits

CREATE TABLE SCM_BUILD_COMMIT_INDEX
(
    BUILD_ID         INTEGER PRIMARY KEY NOT NULL,
    COMMIT_ID        VARCHAR(40)         NOT NULL,
    COMMIT_TIMESTAMP VARCHAR(24)         NOT NULL,
    COMMIT_DATA      JSONB               NOT NULL,
    CONSTRAINT SCM_BUILD_COMMIT_INDEX_FK_BUILD FOREIGN KEY (BUILD_ID) REFERENCES BUILDS (ID) ON DELETE CASCADE
);

CREATE INDEX SCM_BUILD_COMMIT_INDEX_IX_BUILD_ID ON SCM_BUILD_COMMIT_INDEX (BUILD_ID);
CREATE INDEX SCM_BUILD_COMMIT_INDEX_IX_COMMIT_TIMESTAMP ON SCM_BUILD_COMMIT_INDEX (COMMIT_TIMESTAMP);
CREATE UNIQUE INDEX SCM_BUILD_COMMIT_INDEX_UQ_COMMIT_ID ON SCM_BUILD_COMMIT_INDEX (BUILD_ID, COMMIT_ID);
