-- 32. Project favourites (#437)

CREATE TABLE PROJECT_FAVOURITES (
  ID        SERIAL  NOT NULL,
  ACCOUNTID INTEGER NOT NULL,
  PROJECTID INTEGER NOT NULL,
  CONSTRAINT PROJECT_FAVOURITES_PK PRIMARY KEY (ID),
  CONSTRAINT PROJECT_FAVOURITES_UQ UNIQUE (ACCOUNTID, PROJECTID),
  CONSTRAINT PROJECT_FAVOURITES_FK_ACCOUNT FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE,
  CONSTRAINT PROJECT_FAVOURITES_FK_PROJECT FOREIGN KEY (PROJECTID) REFERENCES PROJECTS (ID) ON DELETE CASCADE
);
