-- 72. Jobs history

CREATE TABLE JOB_HISTORY
(
    ID           SERIAL PRIMARY KEY NOT NULL,
    JOB_CATEGORY VARCHAR(255)       NOT NULL,
    JOB_TYPE     VARCHAR(255)       NOT NULL,
    JOB_KEY      VARCHAR(255)       NOT NULL,
    STARTED_AT   VARCHAR(24)        NOT NULL,
    ENDED_AT     VARCHAR(24)        NOT NULL,
    STATUS       VARCHAR(32)        NOT NULL,
    MESSAGE      TEXT               NULL
);

CREATE INDEX JOB_HISTORY_IDX_JOB_KEY ON JOB_HISTORY (JOB_KEY);
CREATE INDEX JOB_HISTORY_IDX_STARTED_AT ON JOB_HISTORY (STARTED_AT);
CREATE INDEX JOB_HISTORY_IDX_ENDED_AT ON JOB_HISTORY (ENDED_AT);
CREATE INDEX JOB_HISTORY_IDX_STATUS ON JOB_HISTORY (STATUS);
CREATE INDEX JOB_HISTORY_IDX_FILTER ON JOB_HISTORY (JOB_KEY, STARTED_AT, ENDED_AT, STATUS);
