-- 73. Auto-versioning trail

CREATE TABLE AV_TRAIL
(
    ID               VARCHAR(36)  NOT NULL PRIMARY KEY,
    PROMOTION_RUN_ID INT          NOT NULL,
    PROJECT          VARCHAR(80)  NOT NULL,
    BRANCH           VARCHAR(120) NOT NULL,
    CONFIGURATION    JSONB        NOT NULL,
    ORDER_ID         VARCHAR(36)  NULL,
    REJECTION_REASON TEXT         NULL,
    CONSTRAINT AV_TRAIL_BRANCH_FK_PROMOTION_RUN FOREIGN KEY (PROMOTION_RUN_ID) REFERENCES PROMOTION_RUNS (ID)
);
