-- 74. Auto-versioning trail cascade

ALTER TABLE AV_TRAIL DROP CONSTRAINT AV_TRAIL_BRANCH_FK_PROMOTION_RUN;
ALTER TABLE AV_TRAIL ADD CONSTRAINT AV_TRAIL_BRANCH_FK_PROMOTION_RUN FOREIGN KEY (PROMOTION_RUN_ID) REFERENCES PROMOTION_RUNS (ID) ON DELETE CASCADE;

