-- 76. Index of SCM commits & issues

CREATE TABLE SCM_INDEX_COMMITS
(
    COMMIT_ID        CHAR(40)     NOT NULL,
    PROJECT_ID       INTEGER      NOT NULL,
    COMMIT_SHORT     CHAR(7)      NOT NULL,
    COMMIT_TIMESTAMP CHAR(24)     NOT NULL,
    MESSAGE          VARCHAR(512) NOT NULL,
    CONSTRAINT SCM_INDEX_COMMITS_PK PRIMARY KEY (PROJECT_ID, COMMIT_ID),
    CONSTRAINT SCM_INDEX_COMMITS_FK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE
);

CREATE INDEX SCM_INDEX_COMMITS_IDX_PROJECT_ID ON SCM_INDEX_COMMITS (PROJECT_ID);
CREATE INDEX SCM_INDEX_COMMITS_IDX_COMMIT_ID ON SCM_INDEX_COMMITS (COMMIT_ID);
CREATE INDEX SCM_INDEX_COMMITS_IDX_COMMIT_SHORT ON SCM_INDEX_COMMITS (COMMIT_SHORT);

CREATE TABLE SCM_INDEX_ISSUES
(
    ISSUE_KEY   VARCHAR(40)  NOT NULL,
    PROJECT_ID  INTEGER      NOT NULL,
    ISSUE_TITLE VARCHAR(100) NOT NULL,
    CONSTRAINT SCM_INDEX_ISSUES_PK PRIMARY KEY (PROJECT_ID, ISSUE_KEY),
    CONSTRAINT SCM_INDEX_ISSUES_FK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE
);

CREATE INDEX SCM_INDEX_ISSUES_IDX_PROJECT_ID ON SCM_INDEX_ISSUES (PROJECT_ID);
CREATE INDEX SCM_INDEX_ISSUES_IDX_COMMIT_ID ON SCM_INDEX_ISSUES (ISSUE_KEY);

CREATE TABLE SCM_INDEX_COMMIT_ISSUES
(
    PROJECT_ID INTEGER     NOT NULL,
    COMMIT_ID  CHAR(40)    NOT NULL,
    ISSUE_KEY  VARCHAR(40) NOT NULL,
    CONSTRAINT SCM_INDEX_COMMIT_ISSUES_PK PRIMARY KEY (PROJECT_ID, COMMIT_ID, ISSUE_KEY),
    CONSTRAINT SCM_INDEX_COMMIT_ISSUES_FK_COMMIT FOREIGN KEY (PROJECT_ID, COMMIT_ID) REFERENCES SCM_INDEX_COMMITS (PROJECT_ID, COMMIT_ID) ON DELETE CASCADE,
    CONSTRAINT SCM_INDEX_COMMIT_ISSUES_FK_ISSUE FOREIGN KEY (PROJECT_ID, ISSUE_KEY) REFERENCES SCM_INDEX_ISSUES (PROJECT_ID, ISSUE_KEY) ON DELETE CASCADE
);

CREATE INDEX SCM_INDEX_COMMIT_ISSUES_IDX_COMMIT ON SCM_INDEX_COMMIT_ISSUES (PROJECT_ID, COMMIT_ID);
CREATE INDEX SCM_INDEX_COMMIT_ISSUES_IDX_ISSUE ON SCM_INDEX_COMMIT_ISSUES (PROJECT_ID, ISSUE_KEY);

CREATE TABLE SCM_INDEX_INGESTION
(
    PROJECT_ID            INTEGER  NOT NULL,
    LAST_INGESTED_AT      CHAR(24) NOT NULL,
    LAST_COMMIT           CHAR(40),
    LAST_COMMIT_TIMESTAMP CHAR(24) NOT NULL,
    CONSTRAINT SCM_INDEX_INGESTION_PK PRIMARY KEY (PROJECT_ID),
    CONSTRAINT SCM_INDEX_INGESTION_FK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE
);
