-- 77. Auto-versioning audit cascade

ALTER TABLE AV_AUDIT DROP CONSTRAINT AV_AUDIT_FK_BRANCH;
ALTER TABLE AV_AUDIT ADD CONSTRAINT AV_AUDIT_FK_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID) ON DELETE CASCADE;
