@startuml
boundary provider
control orchestrator
boundary scheduler

group registration
    orchestrator -> scheduler: schedule(this)
end group

group run
    scheduler -> orchestrator: run
    orchestrator -> provider: Gets list of jobs
    provider --> orchestrator: job + schedules
    orchestrator -> scheduler: schedule + unschedule
end run
@enduml
