-- 19. Predefined promotion levels (#301)

CREATE TABLE PREDEFINED_PROMOTION_LEVELS (
  ID          INTEGER      NOT NULL AUTO_INCREMENT,
  ORDERNB     INTEGER      NOT NULL,
  NAME        VARCHAR(40)  NOT NULL,
  DESCRIPTION VARCHAR(500) NULL,
  IMAGETYPE   VARCHAR(40)  NULL,
  IMAGEBYTES  BLOB         NULL,
  CONSTRAINT PREDEFINED_PROMOTION_LEVELS_PK PRIMARY KEY (ID),
  CONSTRAINT PREDEFINED_PROMOTION_LEVELS_UQ UNIQUE (NAME)
);
