-- 24. Description and expression can be null (#351)

ALTER TABLE BRANCH_TEMPLATE_DEFINITION_PARAMS ALTER COLUMN DESCRIPTION VARCHAR(500) NULL;
ALTER TABLE BRANCH_TEMPLATE_DEFINITION_PARAMS ALTER COLUMN EXPRESSION VARCHAR(500) NULL;
