-- 15. Predefined validation stamps (#263)

CREATE TABLE PREDEFINED_VALIDATION_STAMPS (
  ID              INTEGER      NOT NULL AUTO_INCREMENT,
  NAME            VARCHAR(40)  NOT NULL,
  DESCRIPTION     VARCHAR(500) NOT NULL,
  IMAGETYPE       VARCHAR(40)  NULL,
  IMAGEBYTES      BLOB         NULL,
  CONSTRAINT PREDEFINED_VALIDATION_STAMPS_PK PRIMARY KEY (ID),
  CONSTRAINT PREDEFINED_VALIDATION_STAMPS_UQ UNIQUE (NAME)
);
