-- 13. Not using clobs (#244)

ALTER TABLE BUILD_FILTERS ALTER COLUMN DATA VARCHAR(2000) NOT NULL;
ALTER TABLE CONFIGURATIONS ALTER COLUMN CONTENT VARCHAR(2000) NOT NULL;
ALTER TABLE SETTINGS ALTER COLUMN VALUE VARCHAR(2000) NOT NULL;
ALTER TABLE PREFERENCES ALTER COLUMN CONTENT VARCHAR(2000) NOT NULL;
ALTER TABLE PROPERTIES ALTER COLUMN JSON VARCHAR(2000) NULL;
ALTER TABLE SHARED_BUILD_FILTERS ALTER COLUMN DATA VARCHAR(2000) NOT NULL;
ALTER TABLE BRANCH_TEMPLATE_DEFINITIONS ALTER COLUMN SYNCHRONISATIONSOURCECONFIG VARCHAR(2000) NULL;
