-- 17. Description can be null (#303)

ALTER TABLE PROJECTS ALTER COLUMN DESCRIPTION VARCHAR(500) NULL;
ALTER TABLE BRANCHES ALTER COLUMN DESCRIPTION VARCHAR(500) NULL;
ALTER TABLE BUILDS ALTER COLUMN DESCRIPTION VARCHAR(500) NULL;
ALTER TABLE PROMOTION_LEVELS ALTER COLUMN DESCRIPTION VARCHAR(500) NULL;
ALTER TABLE PROMOTION_RUNS ALTER COLUMN DESCRIPTION VARCHAR(500) NULL;
ALTER TABLE VALIDATION_STAMPS ALTER COLUMN DESCRIPTION VARCHAR(500) NULL;
ALTER TABLE VALIDATION_RUN_STATUSES ALTER COLUMN DESCRIPTION VARCHAR(500) NULL;
