<<<<<<< HEAD
-- 36. Project entity creation (#476)

ALTER TABLE PROJECTS ADD CREATION VARCHAR(24);
ALTER TABLE PROJECTS ADD CREATOR VARCHAR(40);

ALTER TABLE BRANCHES ADD CREATION VARCHAR(24);
ALTER TABLE BRANCHES ADD CREATOR VARCHAR(40);

ALTER TABLE PROMOTION_LEVELS ADD CREATION VARCHAR(24);
ALTER TABLE PROMOTION_LEVELS ADD CREATOR VARCHAR(40);

ALTER TABLE VALIDATION_STAMPS ADD CREATION VARCHAR(24);
ALTER TABLE VALIDATION_STAMPS ADD CREATOR VARCHAR(40);
=======
-- 36. Index on promotion & validation names (#472)

CREATE INDEX IF NOT EXISTS PROMOTION_LEVELS_IX_NAME ON PROMOTION_LEVELS(NAME);
CREATE INDEX IF NOT EXISTS VALIDATION_STAMPS_IX_NAME ON VALIDATION_STAMPS(NAME);
>>>>>>> release/2.28
