-- 41. Validation data for predefined validation stamps (#176)

ALTER TABLE PREDEFINED_VALIDATION_STAMPS
  ADD DATA_TYPE_ID VARCHAR(120) NULL;

ALTER TABLE PREDEFINED_VALIDATION_STAMPS
  ADD DATA_TYPE_CONFIG VARCHAR(10000) NULL;
