-- 38. Validation stamps filters (#265)

CREATE TABLE VALIDATION_STAMP_FILTERS (
  ID      INTEGER        NOT NULL AUTO_INCREMENT,
  NAME    VARCHAR(150)   NOT NULL,
  PROJECT INTEGER        NULL,
  BRANCH  INTEGER        NULL,
  VSNAMES VARCHAR(10000) NOT NULL,
  CONSTRAINT VALIDATION_STAMP_FILTERS_PK PRIMARY KEY (ID),
  CONSTRAINT VALIDATION_STAMP_FILTERS_FK_PROJECT FOREIGN KEY (PROJECT) REFERENCES PROJECTS (ID) ON DELETE CASCADE,
  CONSTRAINT VALIDATION_STAMP_FILTERS_FK_BRANCH FOREIGN KEY (BRANCH) REFERENCES BRANCHES (ID) ON DELETE CASCADE,
  CONSTRAINT VALIDATION_STAMP_FILTERS_UQ_NAME UNIQUE (NAME, PROJECT, BRANCH)
);
