-- 20. Group mappings - for LDAP (#86)

CREATE TABLE ACCOUNT_GROUP_MAPPING (
  ID      INTEGER      NOT NULL AUTO_INCREMENT,
  MAPPING VARCHAR(20)  NOT NULL,
  SOURCE  VARCHAR(200) NOT NULL,
  GROUPID INTEGER      NOT NULL,
  CONSTRAINT ACCOUNT_GROUP_MAPPING_PK PRIMARY KEY (ID),
  CONSTRAINT ACCOUNT_GROUP_MAPPING_UQ UNIQUE (MAPPING, SOURCE),
  CONSTRAINT ACCOUNT_GROUP_MAPPING_ACCOUNT_GROUPS FOREIGN KEY (GROUPID) REFERENCES ACCOUNT_GROUPS (ID)
    ON DELETE CASCADE
);
