version: "2.1"

services:
   postgres:
    image: postgres:11
    environment:
      POSTGRES_DB      : ontrack
      POSTGRES_USER    : ontrack
      POSTGRES_PASSWORD: ontrack
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
      ports:
         - "9200:9200"
         - "9300:9300"
      environment:
         - "discovery.type=single-node"
         - bootstrap.memory_lock=true
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
         memlock:
            soft: -1
            hard: -1


   # Rabbit MQ
   rabbitmq:
      image: rabbitmq:3.13.7-management
      hostname: rabbit
      environment:
         RABBITMQ_DEFAULT_USER: ontrack
         RABBITMQ_DEFAULT_PASS: ontrack
      ports:
         - "15672:15672"
         - "5672:5672"

   ontrack:
      image: "nemerosa/ontrack-extension-test:${VERSION}"
      depends_on:
         postgres:
            condition: service_started
         elasticsearch:
            condition: service_started
      environment:
         PROFILE: acceptance
         SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/ontrack"
         ONTRACK_CONFIG_CONFIGURATION_TEST: "false"
         JAVA_OPTIONS: "-Xmx2048m"
         SPRING_ELASTICSEARCH_URIS: "http://elasticsearch:9200"
         # RabbitMQ
         SPRING_RABBITMQ_HOST: rabbitmq
         SPRING_RABBITMQ_USERNAME: ontrack
         SPRING_RABBITMQ_PASSWORD: ontrack
   selenium:
      image: "selenium/standalone-chrome:3.11.0"
      environment:
         JAVA_OPTS: "-Xmx3072m -Xms3072m"
   ontrack_acceptance:
      image: "nemerosa/ontrack-acceptance:${VERSION:-latest}"
      depends_on:
         ontrack:
            condition: service_healthy
         selenium:
            condition: service_started
      environment:
         ONTRACK_ACCEPTANCE_IMPLICIT_WAIT: 30
         ONTRACK_ACCEPTANCE_SELENIUM_GRID_URL: http://selenium:4444/wd/hub
         ONTRACK_ACCEPTANCE_SELENIUM_BROWSER_NAME: chrome
         ONTRACK_ACCEPTANCE_SELENIUM_TARGET_URL: http://ontrack:8080
         ONTRACK_ACCEPTANCE_TARGET_URL: http://ontrack:8080
         ONTRACK_ACCEPTANCE_CONTEXT: "extensions"
         JAVA_OPTIONS: "-Xmx2048m -Xms2048m"
      volumes:
         - "./build:/ontrack/acceptance/output:rw"
